// Auto-generated by scripts/_split_lr_bank.ts from the original
// listeningReadingQuestions.ts monolith — evaluated and re-serialized from
// the live module, not hand-transcribed, so content is guaranteed identical.
// Do not hand-edit; edit source content upstream and re-run the split if the
// bank is ever restructured again.
import type { PracticeQuestionData } from "@/components/PracticeQuestion";

const questions: PracticeQuestionData[] = [
  {
    image: {
      src: "/images/part1/part1a.jpg",
      credit: "Photo by Shixart1985, CC BY 2.0, via Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:Barista_prepares_espresso_at_coffee_shop.jpg",
      author: "Shixart1985",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A close-up of a barista's hands at an espresso machine. One hand presses a wooden tamper into a portafilter while the other rests on the machine's controls.",
    options: [
      {
        label: "A",
        text: "The barista is wiping down the espresso machine.",
      },
      {
        label: "B",
        text: "The barista is pouring milk into a jug.",
      },
      {
        label: "C",
        text: "The barista is pressing a tamper into a portafilter.",
      },
      {
        label: "D",
        text: "The barista is stamping a customer's loyalty card.",
      },
    ],
    correct: "C",
    explanation:
      "(C) matches the action actually shown — the tamper is being pressed into the portafilter. (D) swaps 'tamping' for the similar-sounding 'stamping,' a classic Part 1 auditory trap. (A) and (B) describe plausible café actions that aren't happening. Part 1 rewards what is visibly true, not what could be true.",
  },
  {
    image: {
      src: "/images/part1/part1b.jpg",
      credit: "Photo by Amit Chattopadhyay, CC BY 2.0, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "Several passengers sit in an airport waiting area. One passenger is reading a newspaper, and bags rest on the floor beside the seats.",
    options: [
      {
        label: "A",
        text: "The passengers are boarding the plane.",
      },
      {
        label: "B",
        text: "A passenger is folding a newspaper.",
      },
      {
        label: "C",
        text: "Bags have been placed on the floor.",
      },
      {
        label: "D",
        text: "The seats are being cleaned.",
      },
    ],
    correct: "C",
    explanation:
      "(C) correctly describes the state of the scene — note the passive 'have been placed.' (A) and (D) name actions no one is performing, and (B) swaps the passenger's real action (reading) for a similar-sounding one (folding) — a classic Part 1 trap.",
  },
  {
    image: {
      src: "/images/part1/part1c.jpg",
      credit: "Photo by David Lucas, Public domain, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A worker in a yellow hard hat operates a pallet jack on a loading dock. Stacks of green plastic crates are piled against the wall to his right.",
    options: [
      {
        label: "A",
        text: "He's loading crates onto a delivery truck.",
      },
      {
        label: "B",
        text: "He's operating a pallet jack.",
      },
      {
        label: "C",
        text: "He's climbing a ladder to reach a top shelf.",
      },
      {
        label: "D",
        text: "He's carrying a crate on his shoulder.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the action actually shown — he's operating the pallet jack. (A) is tempting because crates are visible, but no one is loading them onto a truck; the crates are simply stacked. (C) and (D) describe actions that aren't happening. Watch for statements that name objects you can genuinely see but attach the wrong action to them.",
  },
  {
    image: {
      src: "/images/part1/part1d.jpg",
      credit: "Photo by Shixart1985, CC BY 2.0, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A woman in a dark blazer sits at a desk writing in a notebook with a pen. An open laptop stands on the desk beside her, and a framed picture hangs on the wall behind.",
    options: [
      {
        label: "A",
        text: "She's writing in a notebook.",
      },
      {
        label: "B",
        text: "She's typing on the laptop.",
      },
      {
        label: "C",
        text: "She's hanging a picture on the wall.",
      },
      {
        label: "D",
        text: "She's righting an overturned chair.",
      },
    ],
    correct: "A",
    explanation:
      "(A) describes the visible action — she's writing in the notebook. (B) is the trap: the laptop is right there and open, but her hands are on the pen, not the keyboard. (D) swaps 'writing' for the identical-sounding 'righting,' a classic Part 1 homophone trap. (C) names an object in the scene but an action nobody is performing.",
  },
  {
    image: {
      src: "/images/part1/part1e.jpg",
      credit: "Photo by Mostafameraji, CC0, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A building under construction, seen from a distance. Scaffolding covers the concrete structure. One worker stands on the scaffolding at the left, and two workers in yellow hard hats stand on a platform to the right.",
    options: [
      {
        label: "A",
        text: "Scaffolding has been erected around the building.",
      },
      {
        label: "B",
        text: "The workers are pouring concrete.",
      },
      {
        label: "C",
        text: "A crane is lifting a steel beam.",
      },
      {
        label: "D",
        text: "The workers are removing their hard hats.",
      },
    ],
    correct: "A",
    explanation:
      "(A) correctly describes the state of the scene — note the passive 'has been erected,' which describes a result rather than an action in progress. When a photo is taken from far away and you can't make out precisely what each person is doing, the answer is usually a statement about the setting, not about an individual's action. (B), (C), and (D) all name specific actions that can't be seen.",
  },
  {
    image: {
      src: "/images/part1/part1f.jpg",
      credit: "Photo by Pekka J. Heiskanen, CC BY 4.0, via Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:People_on_the_platform_at_Tikkurila_railway_station_in_Vantaa,_Finland,_2012.jpg",
      author: "Pekka J. Heiskanen",
      licenseName: "CC BY 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by/4.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A green and white train is stopped alongside a covered station platform. A crowd of passengers, many of them children wearing backpacks, walks along the platform beside the train.",
    options: [
      {
        label: "A",
        text: "The train is pulling out of the station.",
      },
      {
        label: "B",
        text: "The platform has been cleared of passengers.",
      },
      {
        label: "C",
        text: "The train is being washed.",
      },
      {
        label: "D",
        text: "Passengers are walking along the platform.",
      },
    ],
    correct: "D",
    explanation:
      "(D) describes what's visibly happening — the passengers are walking along the platform. (A) and (B) both reverse the actual situation: the train is stopped, not departing, and the platform is crowded, not cleared. (C) names an action nobody is performing. Reversals like these are common in Part 1, so listen carefully to the verb.",
  },
  {
    image: {
      src: "/images/part1/part1g.jpg",
      credit: "Photo by PattayaPatrol, CC BY-SA 4.0, via Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:DFC_0796_A_woman_browsing_shirts_on_a_crowded_clothing_rack_in_a_busy_store_with_mannequins_and_folded_garments_nearby.jpg",
      author: "PattayaPatrol",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "In a clothing store, a woman reaches toward a rack of garments on hangers. Two dressed mannequins stand to her left, and folded shirts are displayed on shelves behind her.",
    options: [
      {
        label: "A",
        text: "She's folding shirts into a pile.",
      },
      {
        label: "B",
        text: "She's looking through a rack of clothing.",
      },
      {
        label: "C",
        text: "She's dressing a mannequin.",
      },
      {
        label: "D",
        text: "She's paying at the register.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the action actually shown — she's going through the clothes on the rack. (A) and (C) are traps built from things you really can see: the shirts are already folded and the mannequins are already dressed, but she isn't doing either. (D) describes an action that isn't happening at all.",
  },
  {
    image: {
      src: "/images/part1/part1h.jpg",
      credit: "Photo by Shixart1985, CC BY 2.0, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man wearing a striped apron stands at a kitchen counter, holding a knife in one hand and half a red onion in the other. Another piece of onion rests on a wooden cutting board beside the sink.",
    options: [
      {
        label: "A",
        text: "He's washing vegetables in the sink.",
      },
      {
        label: "B",
        text: "He's putting on an apron.",
      },
      {
        label: "C",
        text: "He's cutting an onion.",
      },
      {
        label: "D",
        text: "He's setting the table for a meal.",
      },
    ],
    correct: "C",
    explanation:
      "(C) matches the action actually shown — he's cutting the onion. (A) and (B) are traps drawn from real details in the photo: there is a sink, and he is wearing an apron, but he isn't washing anything and he put the apron on long before this moment. Part 1 often names something genuinely present and pairs it with the wrong verb.",
  },
  {
    image: {
      src: "/images/part1/part1i.jpg",
      credit: "Photo by CamrynBell, CC BY-SA 4.0, via Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/wiki/File:Book_cart_NBLA.jpg",
      author: "CamrynBell",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A three-shelf library cart stands on a carpeted floor, filled with books shelved upright. There are no people in the photograph.",
    options: [
      {
        label: "A",
        text: "Books have been arranged on a cart.",
      },
      {
        label: "B",
        text: "A librarian is pushing the cart.",
      },
      {
        label: "C",
        text: "The cart's shelves are empty.",
      },
      {
        label: "D",
        text: "Someone is reading at a table.",
      },
    ],
    correct: "A",
    explanation:
      "(A) is correct, and note the passive 'have been arranged' — when a photo contains no people, the answer almost always describes the position or state of objects rather than anyone's action. (B) and (D) are the trap: they invent a person the photo doesn't contain. (C) simply contradicts what you can see.",
  },
  {
    image: {
      src: "/images/part1/part1j.jpg",
      credit: "Photo by PattayaPatrol, CC BY-SA 4.0, via Wikimedia Commons",
      sourceUrl:
        "https://commons.wikimedia.org/wiki/File:DFC_1752_A_vendor_wearing_a_face_mask_hands_a_bag_of_fresh_fruit_to_a_customer_at_a_bustling_outdoor_market_stall_filled_with_bananas_grapes_and_other_produce.jpg",
      author: "PattayaPatrol",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "At a covered market stall, a vendor in an apron reaches across a display of grapes while a customer holds an open plastic bag above the produce. Bunches of bananas fill the front of the stall, and a scale sits on the counter.",
    options: [
      {
        label: "A",
        text: "The vendor is weighing the bananas.",
      },
      {
        label: "B",
        text: "The stall is being packed up for the day.",
      },
      {
        label: "C",
        text: "The vendor is watering plants in a greenhouse.",
      },
      {
        label: "D",
        text: "The customer is holding an open plastic bag.",
      },
    ],
    correct: "D",
    explanation:
      "(D) describes exactly what's visible — the customer holds the bag open over the fruit. (A) is the strongest trap: there really is a scale and there really are bananas, but nothing is on the scale. (C) moves the scene somewhere it isn't, and (B) contradicts the stall's full display.",
  },
  {
    image: {
      src: "/images/part1/part1k.jpg",
      credit: "Photo by Mostafameraji, CC0, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A close-up of a barber's hands at work on a client's dark hair. One hand holds a comb flat against the back of the head while the other works a pair of scissors.",
    options: [
      {
        label: "A",
        text: "The barber is drying the client's hair.",
      },
      {
        label: "B",
        text: "The barber is cutting the client's hair with scissors.",
      },
      {
        label: "C",
        text: "The client is holding a mirror.",
      },
      {
        label: "D",
        text: "The barber is sweeping up hair clippings.",
      },
    ],
    correct: "B",
    explanation:
      "(B) describes the visible action — the scissors are cutting hair. (D) is plausible in a salon and will feel familiar, but sweeping isn't happening here. (A) names a different step in the same routine, and (C) invents a mirror the close-up doesn't show. Choose the statement that survives a look at this photo, not one that fits salons in general.",
  },
  {
    image: {
      src: "/images/part1/part1l.jpg",
      credit: "Photo by Liz Roll, Public domain, via Wikimedia Commons",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "In a warehouse aisle, a man points a handheld barcode scanner at a storage rack. Shrink-wrapped pallets of bottled water are stacked from floor to ceiling on both sides of the aisle.",
    options: [
      {
        label: "A",
        text: "He's driving a forklift down the aisle.",
      },
      {
        label: "B",
        text: "He's unwrapping a pallet of bottles.",
      },
      {
        label: "C",
        text: "He's pointing a scanner at the rack.",
      },
      {
        label: "D",
        text: "He's stacking bottles onto a shelf.",
      },
    ],
    correct: "C",
    explanation:
      "(C) matches the action actually shown — he's aiming the handheld scanner at the rack. (B) and (D) describe things being done to the pallets, but the stock is untouched; it's already wrapped and stacked. (A) puts him on equipment he isn't using. In a warehouse photo, expect several statements that sound like warehouse work but describe the wrong action.",
  },
  {
    image: {
      src: "/images/part1/part1m.jpg",
      credit: "Photo by www.ralfsteinberger.com, CC BY 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/145472109@N04/38075436525",
      author: "www.ralfsteinberger.com",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man in a white shirt pours tea from an ornate metal teapot into a glass, while holding a wooden tray with two more glasses in his other hand.",
    options: [
      {
        label: "A",
        text: "The man is filling the teapot with hot water.",
      },
      {
        label: "B",
        text: "The man is pouring tea into a glass.",
      },
      {
        label: "C",
        text: "The man is handing a tray of glasses to a customer.",
      },
      {
        label: "D",
        text: "The man is washing the teapot in a sink.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — tea is streaming from the teapot into the glass on the tray. (A) reverses the direction of the pour: he is emptying the teapot, not filling it. (C) invents a customer who isn't in the frame — he is simply holding the tray. (D) names an unrelated task; no sink is shown. Part 1 often tests whether you can tell which direction liquid is moving.",
  },
  {
    image: {
      src: "/images/part1/part1n.jpg",
      credit: "Photo by jitze, CC BY 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/40648743@N00/3539498885",
      author: "jitze",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man in a red apron holds a round piece of flattened dough in one hand while pressing a cloth-wrapped tool against the open lid of a large metal oven with the other.",
    options: [
      {
        label: "A",
        text: "The man is removing baked bread from the oven.",
      },
      {
        label: "B",
        text: "The man is shaping a ball of dough with both hands.",
      },
      {
        label: "C",
        text: "The man is holding dough near an open oven.",
      },
      {
        label: "D",
        text: "The man is sweeping the ground near the oven.",
      },
    ],
    correct: "C",
    explanation:
      "(C) matches the scene — the dough is already flattened and held in one hand while the other holds a tool against the raised oven lid. (A) reverses the process: nothing is being taken out, the oven has only just been opened. (B) misdescribes the dough as being actively shaped, when it is simply being held. (D) reassigns the tool to sweeping, a similar-sounding but different task from tending the oven's lid.",
  },
  {
    image: {
      src: "/images/part1/part1o.jpg",
      credit: "Photo by ITRE NCSU, CC BY 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/135892579@N02/20877069430",
      author: "ITRE NCSU",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man wearing glasses works with both hands on a cable attached to a bicycle's handlebar, the bicycle mounted in a repair stand. Rows of wrenches hang on a pegboard on the wall behind him.",
    options: [
      {
        label: "A",
        text: "The man is pumping air into the front tire.",
      },
      {
        label: "B",
        text: "The man is adjusting a cable near the bicycle's handlebar.",
      },
      {
        label: "C",
        text: "The man is hanging a wrench on the pegboard.",
      },
      {
        label: "D",
        text: "The man is removing the front wheel from the bicycle.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches what his hands are actually doing — working the cable near the handlebar. (A) invents a pump that isn't in the picture. (C) reassigns his hands to the wall of wrenches behind him, which sit undisturbed. (D) is wrong in the other direction: the wheel is mounted and in place, not coming off.",
  },
  {
    image: {
      src: "/images/part1/part1p.jpg",
      credit: "Photo by nenad53, CC BY 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/202780880@N02/54576923958",
      author: "nenad53",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man wearing a harness with a gas-powered string trimmer strapped to his back walks through overgrown grass, gripping the trimmer's handle and guiding its head along the ground.",
    options: [
      {
        label: "A",
        text: "The man is raking fallen leaves into a pile.",
      },
      {
        label: "B",
        text: "The man is trimming grass with a string trimmer.",
      },
      {
        label: "C",
        text: "The man is refueling a lawn mower.",
      },
      {
        label: "D",
        text: "The man is watering plants with a hose.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — the trimmer is strapped on and its head is being guided through the grass. (A) and (D) name other yard-work tools that never appear. (C) borrows the fuel tank strapped to his back but misreads it as an act of refueling rather than the engine already in use.",
  },
  {
    image: {
      src: "/images/part1/part1q.jpg",
      credit: "Photo by sunset_removals, CC BY 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/128772241@N07/15578315235",
      author: "sunset_removals",
      licenseName: "CC BY 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man in a high-visibility yellow shirt pushes a two-wheeled hand trolley loaded with three stacked cardboard boxes along a residential street. A moving truck is parked further down the road with its rear doors open.",
    options: [
      {
        label: "A",
        text: "The man is lifting a box out of the truck.",
      },
      {
        label: "B",
        text: "The man is pushing a hand trolley loaded with boxes.",
      },
      {
        label: "C",
        text: "The man is parking the truck at the curb.",
      },
      {
        label: "D",
        text: "The man is opening the truck's rear doors.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — both hands are on the trolley as he wheels the stacked boxes down the street. (A) and (D) describe things happening at the truck, which is parked well behind him and not what his hands are on. (C) invents an action for the truck itself, which is already stationary.",
  },
  {
    image: {
      src: "/images/part1/part1r.jpg",
      credit: "Photo by Moses Cursor Ssebunya, CC0, via Openverse",
      sourceUrl: "https://wordpress.org/photos/photo/98767eaa32/",
      author: "Moses Cursor Ssebunya",
      licenseName: "CC0 1.0",
      licenseUrl: "https://creativecommons.org/publicdomain/zero/1.0/",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A worker in a protective face shield and heavy jacket bends over a metal beam, holding a welding rod that produces a bright spark and rising smoke.",
    options: [
      {
        label: "A",
        text: "The worker is sweeping metal shavings off the floor.",
      },
      {
        label: "B",
        text: "The worker is welding a metal beam.",
      },
      {
        label: "C",
        text: "The worker is lifting the welding machine onto a cart.",
      },
      {
        label: "D",
        text: "The worker is removing his protective gloves.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — the rod is actively striking an arc against the beam, producing the spark and smoke shown. (A) and (D) describe actions that would come after the work is finished, not during it. (C) points at the welding machine sitting idle in the background, which nobody is touching.",
  },
  {
    image: {
      src: "/images/part1/part1s.jpg",
      credit: "Photo by fabola, CC BY-SA 2.0, via Flickr",
      sourceUrl: "https://www.flickr.com/photos/44124339301@N01/15521647911",
      author: "fabola",
      licenseName: "CC BY-SA 2.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A man in a blue hooded sweatshirt points at a projector screen while explaining something to two colleagues seated at a table with an open laptop.",
    options: [
      {
        label: "A",
        text: "The man is closing the laptop on the table.",
      },
      {
        label: "B",
        text: "The man is pointing at the screen while speaking to his colleagues.",
      },
      {
        label: "C",
        text: "The two seated men are taking notes on paper.",
      },
      {
        label: "D",
        text: "The man is turning off the projector.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — he is gesturing toward the screen as he speaks, with both colleagues looking on. (A) and (D) name equipment in the room but describe actions nobody is performing. (C) puts pen to paper for the seated men, when their hands are empty and resting on the table.",
  },
  {
    image: {
      src: "/images/part1/part1t.jpg",
      credit: "Photo by Shingkeevanoma, CC BY-SA 4.0, via Wikimedia Commons",
      sourceUrl: "https://commons.wikimedia.org/w/index.php?curid=36722295",
      author: "Shingkeevanoma",
      licenseName: "CC BY-SA 4.0",
      licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0",
    },
    prompt: "Part 1 · Listen to statements A–D and pick the one that best describes the scene.",
    photo: true,
    audio: {
      label: "Photograph statements",
      durationSec: 0,
    },
    context:
      "A woman in an apron reaches up to wipe a tall glass storefront window with a cloth-wrapped tool, a bucket resting on the sidewalk beside her.",
    options: [
      {
        label: "A",
        text: "The woman is carrying boxes into the store.",
      },
      {
        label: "B",
        text: "The woman is wiping the storefront window.",
      },
      {
        label: "C",
        text: "The woman is sweeping the sidewalk.",
      },
      {
        label: "D",
        text: "The woman is filling the bucket with water.",
      },
    ],
    correct: "B",
    explanation:
      "(B) matches the visible action — both arms are raised, running the cloth-wrapped tool across the glass. (A) reassigns her to the boxes stacked inside the store, which she isn't touching. (C) and (D) invent tasks for the bucket and sidewalk that aren't happening; the bucket sits untouched beside her feet.",
  },
];

export default questions;
