// Auto-generated by scripts/_split_lr_bank.ts from the original
// listeningReadingQuestions.ts monolith — evaluated and re-serialized from
// the live module, not hand-transcribed, so content is guaranteed identical.
// Do not hand-edit; edit source content upstream and re-run the split if the
// bank is ever restructured again.
import type { PracticeQuestionData } from "@/components/PracticeQuestion";

const questions: PracticeQuestionData[] = [
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "When is the quarterly report due?"',
    options: [
      {
        label: "A",
        text: "In the conference room.",
      },
      {
        label: "B",
        text: "By the end of the week.",
      },
      {
        label: "C",
        text: "Yes, I reported it.",
      },
    ],
    correct: "B",
    explanation:
      "'When' asks for a time. 'By the end of the week' answers a time question. (A) answers 'where' and (C) is a yes/no answer that also plays on the word 'report' — a classic Part 2 distractor.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s interviewing the marketing candidate this afternoon?"',
    options: [
      {
        label: "A",
        text: "In the third-floor conference room.",
      },
      {
        label: "B",
        text: "Sandra from HR will handle it.",
      },
      {
        label: "C",
        text: "Sometime around three o'clock.",
      },
    ],
    correct: "B",
    explanation:
      "'Who' asks for a person. 'Sandra from HR' names the person responsible. (A) answers 'where' and (C) answers 'when' — both wrong question types for a 'who' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Where did you send the client\'s shipment?"',
    options: [
      {
        label: "A",
        text: "We shipped it yesterday afternoon.",
      },
      {
        label: "B",
        text: "To our distribution center in Chicago.",
      },
      {
        label: "C",
        text: "About twenty boxes in total.",
      },
    ],
    correct: "B",
    explanation:
      "'Where' asks for a location. 'To our distribution center in Chicago' gives a place. (A) answers 'when' and also echoes the word 'shipment' as 'shipped' — a sound-alike trap — and (C) answers 'how many', a non-sequitur here.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Did you back up the server files before the update?"',
    options: [
      {
        label: "A",
        text: "Yes, I ran it last night before we started.",
      },
      {
        label: "B",
        text: "No, she's not a backup singer anymore.",
      },
      {
        label: "C",
        text: "The server room is on the second floor.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about completing a backup. (A) confirms it was done. (B) is a sound-alike trap playing on 'back up' vs. 'backup singer' and doesn't answer the question, and (C) answers 'where', a wrong question type for a yes/no question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The quarterly budget report is due Friday, isn\'t it?"',
    options: [
      {
        label: "A",
        text: "Yes, that's right — end of day Friday.",
      },
      {
        label: "B",
        text: "It's about fifteen thousand dollars.",
      },
      {
        label: "C",
        text: "I already reported the issue to my manager.",
      },
    ],
    correct: "A",
    explanation:
      "This tag question expects a yes/no confirmation. (A) confirms the deadline directly. (B) answers a 'how much' question that wasn't asked, a non-sequitur, and (C) is a sound-alike trap swapping 'report' (noun) for 'reported' (verb) without confirming the deadline.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "I think we should book the earlier flight to Chicago."',
    options: [
      {
        label: "A",
        text: "That works for me — I'll change the reservation now.",
      },
      {
        label: "B",
        text: "The flight attendant was very helpful.",
      },
      {
        label: "C",
        text: "We booked the hotel last week.",
      },
    ],
    correct: "A",
    explanation:
      "This is a statement suggesting an action, which requires a reactive response of agreement or disagreement. (A) agrees and acts on it. (B) is a plausible-sounding non-sequitur about a past flight, and (C) is a sound-alike trap reusing 'booked' for an unrelated topic (the hotel) instead of responding to the suggestion.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Should we hold the training session in the main hall or the small conference room?"',
    options: [
      {
        label: "A",
        text: "The small room would be better — we're only expecting ten people.",
      },
      {
        label: "B",
        text: "Yes, we should hold it next week.",
      },
      {
        label: "C",
        text: "I held the door open for her.",
      },
    ],
    correct: "A",
    explanation:
      "This is an 'or' choice question, which requires picking one of the two named options rather than a yes/no answer. (A) selects a choice with a reason. (B) incorrectly treats it as a yes/no question, and (C) is a sound-alike trap on 'hold' used in an unrelated sense.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why did the client cancel their order?"',
    options: [
      {
        label: "A",
        text: "They found a cheaper supplier.",
      },
      {
        label: "B",
        text: "Mr. Chen handled that account.",
      },
      {
        label: "C",
        text: "It was cancelled on Tuesday.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason. 'They found a cheaper supplier' gives one. (B) answers 'who', a wrong question type, and (C) answers 'when' while also repeating 'cancel' as 'cancelled' — a sound-alike trap that avoids stating a reason.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How do I reset my password for the new expense system?"',
    options: [
      {
        label: "A",
        text: "Click the 'Forgot Password' link on the login page.",
      },
      {
        label: "B",
        text: "It was reset about twenty minutes ago.",
      },
      {
        label: "C",
        text: "The IT helpdesk is on the third floor.",
      },
    ],
    correct: "A",
    explanation:
      "'How' asks for a method or process. Clicking the reset link explains the procedure. (B) answers 'when' and (C) answers 'where' — both wrong question types for a 'how' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How many units did we sell during the weekend clearance sale?"',
    options: [
      {
        label: "A",
        text: "We moved about three hundred units.",
      },
      {
        label: "B",
        text: "The sale runs through this weekend.",
      },
      {
        label: "C",
        text: "Yes, the discount was quite popular.",
      },
    ],
    correct: "A",
    explanation:
      "'How many' asks for a quantity. Only (A) gives a number. (B) answers 'how long' the sale lasts, and (C) is a yes/no reply, which doesn't fit a quantity question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Isn\'t the new assembly line supposed to start today?"',
    options: [
      {
        label: "A",
        text: "Yes, it's scheduled to go live this afternoon.",
      },
      {
        label: "B",
        text: "No, we assembled it ourselves.",
      },
      {
        label: "C",
        text: "It's on the second floor.",
      },
    ],
    correct: "A",
    explanation:
      "Negative questions like 'Isn't...' still expect a yes/no confirmation. (A) confirms the schedule directly. (B) is a same-sound trap using 'assembled' instead of addressing the timing, and (C) answers 'where', not the yes/no question asked.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Do you know when the contract needs to be signed?"',
    options: [
      {
        label: "A",
        text: "By the end of this week, I believe.",
      },
      {
        label: "B",
        text: "Yes, I know the client well.",
      },
      {
        label: "C",
        text: "The lawyer's office is downtown.",
      },
    ],
    correct: "A",
    explanation:
      "This is an embedded question — the real question is 'when does the contract need to be signed?' (A) gives a deadline. (B) mistakenly treats 'Do you know' as a literal yes/no question about personal acquaintance, and (C) answers 'where'.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "What\'s the asking price for the downtown office space?"',
    options: [
      {
        label: "A",
        text: "It's listed at $4,200 a month.",
      },
      {
        label: "B",
        text: "It's available starting next month.",
      },
      {
        label: "C",
        text: "The realtor showed it to three clients.",
      },
    ],
    correct: "A",
    explanation:
      "'What's the price' asks for a monetary figure. Only (A) provides one. (B) answers 'when' it's available, and (C) answers 'who' viewed it — both wrong question types.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: "Question: \"The patient's insurance is still valid, isn't it?\"",
    options: [
      {
        label: "A",
        text: "Yes, it doesn't expire until December.",
      },
      {
        label: "B",
        text: "No, she hasn't validated her parking yet.",
      },
      {
        label: "C",
        text: "The appointment is at 2 PM.",
      },
    ],
    correct: "A",
    explanation:
      "This tag question asks for confirmation about the insurance status. (A) confirms it directly with a supporting detail. (B) is a same-sound trap swapping 'valid' for 'validated' (parking), and (C) is a non-sequitur about scheduling.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Would you like the buffet option or the plated dinner service for the gala?"',
    options: [
      {
        label: "A",
        text: "Let's go with the buffet — it's more casual.",
      },
      {
        label: "B",
        text: "Yes, that sounds great.",
      },
      {
        label: "C",
        text: "The gala starts at seven.",
      },
    ],
    correct: "A",
    explanation:
      "Or-choice questions require picking one of the two options offered. (A) selects the buffet. (B) incorrectly answers with a plain yes/no, which doesn't work for an 'or' question, and (C) answers 'when', not which option.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "We just received a complaint about a delivery delay."',
    options: [
      {
        label: "A",
        text: "I'll call the customer right away to check the tracking and apologize.",
      },
      {
        label: "B",
        text: "The warehouse ships every day at noon.",
      },
      {
        label: "C",
        text: "That complaint sounds delightful.",
      },
    ],
    correct: "A",
    explanation:
      "This is a statement requiring an appropriate reaction, not an answer to a wh-question. (A) responds with a logical next step. (B) is an unrelated fact about shipping schedules, and (C) uses a similar-sounding word ('delightful') that clashes with the negative context — an implausible reaction.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why was the concrete pour postponed until tomorrow?"',
    options: [
      {
        label: "A",
        text: "Because the weather forecast predicts heavy rain this afternoon.",
      },
      {
        label: "B",
        text: "It was poured on the east wing last week.",
      },
      {
        label: "C",
        text: "The site foreman starts at seven.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason. Heavy rain justifies the postponement. (B) reuses 'poured' but describes an unrelated past event, and (C) is an unrelated fact about the foreman's schedule.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why did the hotel switch to a new laundry service?"',
    options: [
      {
        label: "A",
        text: "The previous company kept losing linens.",
      },
      {
        label: "B",
        text: "The switch is located near the lobby.",
      },
      {
        label: "C",
        text: "We have two hundred rooms available.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason behind the change. Losing linens explains the switch. (B) plays on 'switch' as a light switch rather than the verb 'to switch,' and (C) is an unrelated fact about room capacity.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s leading the new teacher orientation next week?"',
    options: [
      {
        label: "A",
        text: "Ms. Reynolds from the curriculum department.",
      },
      {
        label: "B",
        text: "It starts at nine on Monday.",
      },
      {
        label: "C",
        text: "The orientation packet is in the main office.",
      },
    ],
    correct: "A",
    explanation:
      "'Who' asks for a person's identity. Ms. Reynolds is the named leader. (B) answers 'when' and (C) answers 'where' — both wrong question types for a 'who' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who approved the final cover design for the novel?"',
    options: [
      {
        label: "A",
        text: "The editorial director signed off on it yesterday.",
      },
      {
        label: "B",
        text: "The design took about three weeks to finish.",
      },
      {
        label: "C",
        text: "I really like the color scheme they chose.",
      },
    ],
    correct: "A",
    explanation:
      "'Who' asks for the person responsible. The editorial director is the answer. (B) answers 'how long' and (C) offers a personal opinion rather than naming who approved it.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Did the wheat shipment clear customs inspection?"',
    options: [
      {
        label: "A",
        text: "Yes, it passed without any issues this morning.",
      },
      {
        label: "B",
        text: "The shipment weighs about twenty tons.",
      },
      {
        label: "C",
        text: "Customs officers usually clear paperwork by noon.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about a specific shipment's status. (A) directly confirms it passed. (B) states the shipment's weight, not its customs status, and (C) is a general statement about customs timing that doesn't confirm whether this shipment cleared.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Has the recall notice been sent to all affected owners?"',
    options: [
      {
        label: "A",
        text: "Not yet, we're still finalizing the mailing list.",
      },
      {
        label: "B",
        text: "The recall covers about ten thousand vehicles.",
      },
      {
        label: "C",
        text: "Owners can visit any authorized dealership.",
      },
    ],
    correct: "A",
    explanation:
      "This yes/no question asks about the notice's send status. (A) answers directly with 'not yet.' (B) states the scope of the recall rather than confirming whether notices were sent, and (C) gives unrelated advice for owners.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The new fiber lines are finished, aren\'t they?"',
    options: [
      {
        label: "A",
        text: "Yes, the installation crew completed them this morning.",
      },
      {
        label: "B",
        text: "The waiting lines were pretty long today.",
      },
      {
        label: "C",
        text: "We ordered extra cable last week.",
      },
    ],
    correct: "A",
    explanation:
      "Tag questions expect a yes/no confirmation. (A) confirms completion. (B) reuses 'lines' to mean queues rather than fiber cables, and (C) is a related but non-responsive fact about ordering cable, not confirming completion.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: "Question: \"The gala raised more than last year's event, didn't it?\"",
    options: [
      {
        label: "A",
        text: "Yes, we exceeded last year's total by fifteen percent.",
      },
      {
        label: "B",
        text: "The gala was held at the downtown ballroom.",
      },
      {
        label: "C",
        text: "About three hundred guests attended.",
      },
    ],
    correct: "A",
    explanation:
      "This tag question expects confirmation about the amount raised. (A) confirms it directly. (B) answers 'where' the event was held, and (C) states attendance figures rather than confirming the fundraising total.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Should we pour the foundation on Thursday, or wait until the inspector signs off?"',
    options: [
      {
        label: "A",
        text: "Let's wait for the inspector's approval first.",
      },
      {
        label: "B",
        text: "The foundation is twelve inches thick.",
      },
      {
        label: "C",
        text: "The inspector arrives every Thursday.",
      },
    ],
    correct: "A",
    explanation:
      "This is an 'or' choice question offering two options. (A) selects one option directly. (B) is an unrelated fact about the foundation's thickness, and (C) recombines words from both choices without actually choosing one.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Would you like the ocean-view room, or the one facing the garden?"',
    options: [
      {
        label: "A",
        text: "The ocean-view room sounds perfect, thank you.",
      },
      {
        label: "B",
        text: "The garden was replanted last spring.",
      },
      {
        label: "C",
        text: "Check-out is at eleven a.m.",
      },
    ],
    correct: "A",
    explanation:
      "This 'or' question asks the listener to pick one room type. (A) clearly selects the ocean-view room. (B) reuses 'garden' to describe landscaping rather than choosing that room, and (C) is unrelated information about check-out time.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The workshop materials haven\'t arrived from the printer yet."',
    options: [
      {
        label: "A",
        text: "I'll call them right now to check on the delivery.",
      },
      {
        label: "B",
        text: "The workshop is scheduled for three hours.",
      },
      {
        label: "C",
        text: "Printers in the lab need new ink cartridges.",
      },
    ],
    correct: "A",
    explanation:
      "This statement calls for an appropriate reaction to a problem. (A) proposes a logical next step. (B) is an unrelated fact about the workshop's length, and (C) reuses 'printer' to refer to lab equipment rather than addressing the missing materials.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "Sales of the paperback edition dropped sharply last quarter."',
    options: [
      {
        label: "A",
        text: "Maybe we should run a discount promotion.",
      },
      {
        label: "B",
        text: "The paperback has three hundred pages.",
      },
      {
        label: "C",
        text: "Our hardcover sales are shipped from the main warehouse.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about declining sales calls for a suggested response. (A) proposes an appropriate action. (B) is an unrelated fact about the book's length, and (C) mentions a different edition's shipping process rather than addressing the sales drop.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why was the 6:45 departure to Chicago delayed?"',
    options: [
      {
        label: "A",
        text: "A mechanical issue turned up during the pre-flight inspection.",
      },
      {
        label: "B",
        text: "About forty passengers checked in at the gate.",
      },
      {
        label: "C",
        text: "It departs from gate twelve.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason for the delay. (A) gives the cause. (B) mentions the gate but answers an unrelated question about passenger numbers, and (C) states the departure gate, which answers 'where,' not 'why.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s directing the reshoots next week?"',
    options: [
      {
        label: "A",
        text: "The same director who shot the original scenes.",
      },
      {
        label: "B",
        text: "We reshot that scene twice yesterday.",
      },
      {
        label: "C",
        text: "Next week works fine for me.",
      },
    ],
    correct: "A",
    explanation:
      "'Who' asks for a person. (A) names the director. (B) reuses 'reshot' but describes a past event rather than naming a person, and (C) mistakenly answers a 'when' question about availability.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Should I file the claim online or call the claims office?"',
    options: [
      {
        label: "A",
        text: "Online would be quicker since the phone lines are backed up.",
      },
      {
        label: "B",
        text: "The claim was approved last Tuesday.",
      },
      {
        label: "C",
        text: "I always file my taxes online in April.",
      },
    ],
    correct: "A",
    explanation:
      "This is an or-choice question asking which filing method to use. (A) picks 'online' and justifies it. (B) refers to an unrelated past approval, and (C) reuses 'file... online' but talks about taxes, not the insurance claim.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Is the pool open for lap swimming this morning?"',
    options: [
      {
        label: "A",
        text: "Yes, but only until nine because of a swim class.",
      },
      {
        label: "B",
        text: "The gym opens at six on weekdays.",
      },
      {
        label: "C",
        text: "We're planning to build a second pool next year.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about the pool's morning hours. (A) confirms availability with a time limit. (B) describes a different facility, the gym, and (C) reuses 'pool' but refers to a future construction plan, not today's hours.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "When does the recycling truck usually come by?"',
    options: [
      {
        label: "A",
        text: "Every other Thursday, early in the morning.",
      },
      {
        label: "B",
        text: "It collects paper, glass, and plastic.",
      },
      {
        label: "C",
        text: "The truck was repainted last month.",
      },
    ],
    correct: "A",
    explanation:
      "'When' asks for a time. (A) gives the collection schedule. (B) describes what the truck collects, answering 'what,' not 'when,' and (C) reuses 'truck' but describes an unrelated repainting job.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: "Question: \"The vet said the dog's stitches should come out by Friday, didn't she?\"",
    options: [
      {
        label: "A",
        text: "Yes, that's exactly what she told us at the last visit.",
      },
      {
        label: "B",
        text: "The dog is due for a rabies booster soon.",
      },
      {
        label: "C",
        text: "She stitched up a tear in the couch cushion.",
      },
    ],
    correct: "A",
    explanation:
      "This is a tag question seeking confirmation of what the vet said. (A) confirms it directly. (B) is an unrelated fact about vaccinations, and (C) reuses 'stitched' but describes mending furniture, not the dog's medical care.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Do you happen to know where the spare projector bulb is kept?"',
    options: [
      {
        label: "A",
        text: "It's in the supply closet next to the printer.",
      },
      {
        label: "B",
        text: "Yes, I've changed one before.",
      },
      {
        label: "C",
        text: "The projector needs a new bulb every eight months.",
      },
    ],
    correct: "A",
    explanation:
      "This is an embedded question — the real question is 'where is the spare bulb kept?' (A) states the location. (B) mistakes 'Do you know' for a literal yes/no question and confirms familiarity without giving a location, and (C) is an unrelated fact about replacement frequency rather than where the bulb is stored.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context:
      'Statement: "Our biggest wholesale client is renegotiating their contract terms this week."',
    options: [
      {
        label: "A",
        text: "I'll pull together the account history so we're prepared for the discussion.",
      },
      {
        label: "B",
        text: "The client placed their first order two years ago.",
      },
      {
        label: "C",
        text: "Wholesale prices tend to rise in the summer.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about an upcoming negotiation calls for an appropriate reaction. (A) proposes a useful next step. (B) is an unrelated fact about the client's history rather than a response to the renegotiation, and (C) reuses 'wholesale' but makes a general seasonal claim that doesn't address this week's contract talks.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How long will the road resurfacing project take?"',
    options: [
      {
        label: "A",
        text: "About three weeks, weather permitting.",
      },
      {
        label: "B",
        text: "It starts on Monday morning.",
      },
      {
        label: "C",
        text: "The crew resurfaced two miles last month.",
      },
    ],
    correct: "A",
    explanation:
      "'How long' asks for a duration. (A) gives one. (B) answers 'when' the project begins, not how long it lasts, and (C) reuses 'resurfaced' but describes a separate, already-completed job rather than stating the current project's length.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Would you rather present the findings yourself, or have someone from the research team do it?"',
    options: [
      {
        label: "A",
        text: "I'd prefer to present it myself, since I know the data best.",
      },
      {
        label: "B",
        text: "Yes, the findings were quite surprising.",
      },
      {
        label: "C",
        text: "The research team meets every Tuesday.",
      },
    ],
    correct: "A",
    explanation:
      "This is an or-choice question offering two options for who presents. (A) clearly selects one. (B) answers with a plain yes/no, which doesn't fit an 'or' question, and (C) reuses 'research team' but states a meeting schedule instead of choosing who will present.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: "Question: \"What's the main topic on tomorrow's board meeting agenda?\"",
    options: [
      {
        label: "A",
        text: "The proposed merger with Fenwick Corp.",
      },
      {
        label: "B",
        text: "It starts at nine sharp.",
      },
      {
        label: "C",
        text: "The boardroom seats twelve people.",
      },
    ],
    correct: "A",
    explanation:
      "'What' asks for the topic. (A) names it directly. (B) answers 'when' the meeting starts, a wrong question type, and (C) is an unrelated fact about the room's seating capacity.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Has the loan application been approved yet?"',
    options: [
      {
        label: "A",
        text: "Not yet — the underwriter needs two more days.",
      },
      {
        label: "B",
        text: "The interest rate is quite competitive.",
      },
      {
        label: "C",
        text: "We approved of the new office decor.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about the application's status. (A) answers directly with 'not yet.' (B) is a related but non-responsive fact about the rate, not the approval status, and (C) is a sound-alike trap reusing 'approved' to mean 'liked' rather than confirming the loan decision.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The software subscription renews automatically next month, doesn\'t it?"',
    options: [
      {
        label: "A",
        text: "Yes, unless we cancel it before the billing date.",
      },
      {
        label: "B",
        text: "The update added several new features.",
      },
      {
        label: "C",
        text: "We subscribe to three trade magazines.",
      },
    ],
    correct: "A",
    explanation:
      "This tag question expects a yes/no confirmation about auto-renewal. (A) confirms it directly. (B) is an unrelated fact about a software update, and (C) is a sound-alike trap reusing 'subscribe' for magazines instead of confirming the software's renewal.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Would you like the photos printed on matte paper or glossy paper?"',
    options: [
      {
        label: "A",
        text: "Matte, please — it won't show fingerprints.",
      },
      {
        label: "B",
        text: "Yes, they turned out beautifully.",
      },
      {
        label: "C",
        text: "The photographer arrives at noon.",
      },
    ],
    correct: "A",
    explanation:
      "This is an 'or' choice question offering two paper finishes. (A) selects matte with a reason. (B) incorrectly answers with a plain yes/no, which doesn't fit an 'or' question, and (C) is an unrelated fact about the photographer's arrival time.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Do you know which platform the express train to Leeds leaves from?"',
    options: [
      {
        label: "A",
        text: "Platform six, according to the departure board.",
      },
      {
        label: "B",
        text: "Yes, I've ridden that train many times.",
      },
      {
        label: "C",
        text: "The express train takes about ninety minutes.",
      },
    ],
    correct: "A",
    explanation:
      "This is an embedded question — the real question is 'which platform does the train leave from?' (A) states the platform. (B) mistakes 'Do you know' for a literal yes/no question, confirming familiarity without giving a platform, and (C) answers 'how long' the trip takes, not 'which platform.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The production server crashed twice this morning."',
    options: [
      {
        label: "A",
        text: "I'll check the error logs and loop in the on-call engineer.",
      },
      {
        label: "B",
        text: "The server room was renovated last year.",
      },
      {
        label: "C",
        text: "Crash test results for the new model looked promising.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about a technical problem calls for an appropriate reaction. (A) proposes a logical next step. (B) is an unrelated fact about the room's renovation, and (C) is a sound-alike trap reusing 'crash' in the unrelated sense of vehicle crash tests.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How much does it cost to rent the moving truck for a full day?"',
    options: [
      {
        label: "A",
        text: "About ninety dollars, plus mileage.",
      },
      {
        label: "B",
        text: "It seats up to three people.",
      },
      {
        label: "C",
        text: "The truck was rented out all weekend.",
      },
    ],
    correct: "A",
    explanation:
      "'How much' asks for a cost. (A) gives the price. (B) states seating capacity, answering 'how many' rather than the price, and (C) is a sound-alike trap reusing 'rented' to describe someone else's usage instead of stating the daily rate.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "When is my performance review scheduled?"',
    options: [
      {
        label: "A",
        text: "In Room 204, down the hall.",
      },
      {
        label: "B",
        text: "Yes, it was already reviewed.",
      },
      {
        label: "C",
        text: "Next Tuesday at ten o'clock.",
      },
    ],
    correct: "C",
    explanation:
      "'When' asks for a time. 'Next Tuesday at ten o'clock' gives one. (A) answers 'where', a wrong question type, and (B) is a sound-alike trap treating 'review' as a yes/no verb instead of naming a date.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Did you submit the expense report for the sales trip?"',
    options: [
      {
        label: "A",
        text: "Yes, I submitted it this morning.",
      },
      {
        label: "B",
        text: "The trip lasted five days.",
      },
      {
        label: "C",
        text: "The expenses were quite high this time.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about whether the report was submitted. (A) confirms it directly. (B) is an unrelated fact about the trip's length, and (C) reuses 'expenses' but comments on the amount instead of confirming submission.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The new payroll system goes live next Monday, doesn\'t it?"',
    options: [
      {
        label: "A",
        text: "Pay stubs are emailed automatically each cycle.",
      },
      {
        label: "B",
        text: "Yes, IT finished the migration yesterday.",
      },
      {
        label: "C",
        text: "I usually get paid twice a month.",
      },
    ],
    correct: "B",
    explanation:
      "This tag question expects a yes/no confirmation about the launch date. (B) confirms it directly. (A) is a related but non-responsive fact about how stubs are delivered, and (C) is a sound-alike trap reusing 'pay' to describe personal pay frequency rather than confirming the system's go-live date.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Should we schedule the vendor meeting for Tuesday or Wednesday?"',
    options: [
      {
        label: "A",
        text: "Yes, that works for everyone.",
      },
      {
        label: "B",
        text: "The vendor supplies our office furniture.",
      },
      {
        label: "C",
        text: "Wednesday would be better — Tuesday's fully booked.",
      },
    ],
    correct: "C",
    explanation:
      "This 'or' choice question requires picking one of the two named days. (C) selects Wednesday with a reason. (A) incorrectly answers with a plain yes/no, which doesn't fit an 'or' question, and (B) is an unrelated fact about what the vendor supplies.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why did the inventory count come up short this quarter?"',
    options: [
      {
        label: "A",
        text: "Several pallets were mislabeled during the audit.",
      },
      {
        label: "B",
        text: "The warehouse counts inventory every quarter.",
      },
      {
        label: "C",
        text: "It was counted by hand this time.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason. Mislabeled pallets explain the shortfall. (B) is a general non-sequitur about how often counts happen, and (C) answers 'how' the count was done, a wrong question type for 'why.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How do I join today\'s video conference call?"',
    options: [
      {
        label: "A",
        text: "It starts at two o'clock.",
      },
      {
        label: "B",
        text: "Click the link in the calendar invite.",
      },
      {
        label: "C",
        text: "The conference room seats twenty people.",
      },
    ],
    correct: "B",
    explanation:
      "'How' asks for a method. Clicking the invite link explains the process. (A) answers 'when' the call starts, and (C) is a sound-alike trap swapping 'conference call' for a physical 'conference room' instead of describing how to join.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context:
      'Statement: "Several employees still haven\'t received their new parking permits for the office relocation."',
    options: [
      {
        label: "A",
        text: "I'll follow up with building management today.",
      },
      {
        label: "B",
        text: "The new office is closer to the highway.",
      },
      {
        label: "C",
        text: "Parking downtown is quite expensive.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about a problem calls for an appropriate reaction. (A) proposes a logical next step. (B) is an unrelated fact about the relocation itself, and (C) reuses 'parking' but makes a general cost comment instead of addressing the missing permits.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s catering the retirement party on Friday?"',
    options: [
      {
        label: "A",
        text: "It starts at noon.",
      },
      {
        label: "B",
        text: "Riverside Deli is handling it this time.",
      },
      {
        label: "C",
        text: "The party room seats fifty guests.",
      },
    ],
    correct: "B",
    explanation:
      "'Who' asks for the person or company responsible. Riverside Deli names them. (A) answers 'when' the party starts, and (C) is an unrelated fact about room capacity — neither identifies who's catering.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Has the new printer been installed in the design studio?"',
    options: [
      {
        label: "A",
        text: "Not yet, IT is coming next Tuesday.",
      },
      {
        label: "B",
        text: "The studio just got repainted.",
      },
      {
        label: "C",
        text: "We printed five hundred flyers.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about installation status. (A) answers directly with 'not yet.' (B) is an unrelated fact about the studio's paint job, and (C) is a sound-alike trap reusing 'printer' as 'printed' to describe an unrelated task rather than confirming installation.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The annual audit starts next Monday, doesn\'t it?"',
    options: [
      {
        label: "A",
        text: "The auditors specialize in tax compliance.",
      },
      {
        label: "B",
        text: "We audited the warehouse twice last year.",
      },
      {
        label: "C",
        text: "Yes, the accounting team already prepared the files.",
      },
    ],
    correct: "C",
    explanation:
      "Tag questions expect a yes/no confirmation. (C) confirms the timing directly. (A) is an unrelated fact about the auditors' specialty, and (B) reuses 'audited' to describe a different, already-completed event rather than confirming next Monday's start.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Would you prefer the window seat or the aisle seat for the flight?"',
    options: [
      {
        label: "A",
        text: "The flight departs at six.",
      },
      {
        label: "B",
        text: "Seat belts must stay fastened during takeoff.",
      },
      {
        label: "C",
        text: "I'll take the aisle seat, thanks.",
      },
    ],
    correct: "C",
    explanation:
      "Or-choice questions require picking one of the two named options. (C) selects the aisle seat. (A) answers 'when' the flight leaves, a wrong question type, and (B) is a plausible-sounding but irrelevant safety reminder that doesn't choose a seat.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The conference Wi-Fi keeps disconnecting during presentations."',
    options: [
      {
        label: "A",
        text: "I'll ask the IT team to check the router.",
      },
      {
        label: "B",
        text: "We connected with several new clients last week.",
      },
      {
        label: "C",
        text: "The conference room holds two hundred people.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about a technical problem calls for an appropriate reaction. (A) proposes a logical next step. (B) is a sound-alike trap reusing 'connected' in the unrelated sense of networking with clients, and (C) is an unrelated fact about room capacity.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Where should I drop off the signed vendor contracts?"',
    options: [
      {
        label: "A",
        text: "They were signed this morning.",
      },
      {
        label: "B",
        text: "At the front desk, in the blue folder.",
      },
      {
        label: "C",
        text: "The vendor offers a ten percent discount.",
      },
    ],
    correct: "B",
    explanation:
      "'Where' asks for a location. (B) gives the drop-off spot. (A) answers 'when' they were signed, a wrong question type, and (C) is an unrelated fact about vendor pricing.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Where do new hires pick up their building access badge?"',
    options: [
      {
        label: "A",
        text: "The badge system was upgraded last year.",
      },
      {
        label: "B",
        text: "At the security desk in the main lobby.",
      },
      {
        label: "C",
        text: "New hires start on Mondays.",
      },
    ],
    correct: "B",
    explanation:
      "'Where' asks for a location. 'At the security desk in the main lobby' gives one. (A) is an unrelated fact about a past system upgrade, and (C) answers 'when' hires start, a wrong question type for 'where.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Has the security patch been installed on all the laptops?"',
    options: [
      {
        label: "A",
        text: "Yes, IT pushed it out to every device last night.",
      },
      {
        label: "B",
        text: "The patch covers three known vulnerabilities.",
      },
      {
        label: "C",
        text: "Laptops are issued during orientation.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about installation status. (A) confirms it directly. (B) is a related but non-responsive fact about what the patch fixes, not whether it was installed, and (C) is an unrelated fact about when laptops are issued.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The new dinosaur exhibit opens to the public next Saturday, doesn\'t it?"',
    options: [
      {
        label: "A",
        text: "The museum expanded its gift shop last year.",
      },
      {
        label: "B",
        text: "Exhibits are usually sponsored by local businesses.",
      },
      {
        label: "C",
        text: "Yes, the ribbon-cutting is scheduled for ten a.m.",
      },
    ],
    correct: "C",
    explanation:
      "This tag question expects a yes/no confirmation of the opening date. (C) confirms it directly. (A) is an unrelated fact about the gift shop, and (B) is a general non-sequitur about sponsorship rather than confirming Saturday's opening.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Should we print the brochures in-house, or send the job to an outside print shop?"',
    options: [
      {
        label: "A",
        text: "Let's send it out — our printer can't handle that paper stock.",
      },
      {
        label: "B",
        text: "Yes, the brochures look great.",
      },
      {
        label: "C",
        text: "The print shop is next to the bakery.",
      },
    ],
    correct: "A",
    explanation:
      "This is an 'or' choice question requiring one of the two named options. (A) selects the outside print shop with a reason. (B) incorrectly answers with a plain yes/no, which doesn't fit an 'or' question, and (C) is an unrelated fact about the shop's location rather than a choice.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The pharmacy says this medication is on backorder for two weeks."',
    options: [
      {
        label: "A",
        text: "The pharmacy just renovated its front counter.",
      },
      {
        label: "B",
        text: "I'll ask the doctor about a substitute in the meantime.",
      },
      {
        label: "C",
        text: "Orders usually ship within two business days.",
      },
    ],
    correct: "B",
    explanation:
      "This statement about a delay calls for an appropriate reaction. (B) proposes a logical next step. (A) is an unrelated fact about the pharmacy's counter, and (C) is a sound-alike trap reusing 'order' from 'backorder' to state an unrelated shipping policy instead of addressing the two-week delay.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How much does it cost to rent a booth at the trade show?"',
    options: [
      {
        label: "A",
        text: "It's held in the convention center downtown.",
      },
      {
        label: "B",
        text: "Booths are usually ten feet by ten feet.",
      },
      {
        label: "C",
        text: "About twelve hundred dollars for a standard space.",
      },
    ],
    correct: "C",
    explanation:
      "'How much' asks for a cost. Only (C) gives a price. (A) answers 'where' the show is held, and (B) states booth dimensions, answering a size question rather than the cost — both wrong question types.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s reviewing the research grant applications this year?"',
    options: [
      {
        label: "A",
        text: "A committee from the dean's office.",
      },
      {
        label: "B",
        text: "Applications are due by the end of March.",
      },
      {
        label: "C",
        text: "The grant covers lab equipment and travel.",
      },
    ],
    correct: "A",
    explanation:
      "'Who' asks for a person or group. (A) names the reviewing committee. (B) answers 'when' applications are due, and (C) answers 'what' the grant covers — both wrong question types for 'who.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How do I submit a reimbursement request for travel expenses?"',
    options: [
      {
        label: "A",
        text: "Fill out the online form and attach your receipts.",
      },
      {
        label: "B",
        text: "The trip lasted three days.",
      },
      {
        label: "C",
        text: "Travel expenses were higher this quarter.",
      },
    ],
    correct: "A",
    explanation:
      "'How' asks for a method. Filling out the form describes the process. (B) answers 'how long' the trip was, and (C) is an unrelated fact about cost — both wrong question types for a 'how' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who\'s proofreading the annual report before it goes to print?"',
    options: [
      {
        label: "A",
        text: "It goes to print next Friday.",
      },
      {
        label: "B",
        text: "Our copyediting team is handling it this year.",
      },
      {
        label: "C",
        text: "The report is forty pages long.",
      },
    ],
    correct: "B",
    explanation:
      "'Who' asks for a person or group. 'Our copyediting team' names them. (A) answers 'when' and (C) answers 'how long' — both wrong question types for a 'who' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Did the courier already pick up the outgoing packages?"',
    options: [
      {
        label: "A",
        text: "Yes, right around noon.",
      },
      {
        label: "B",
        text: "He picked up a new hobby last month.",
      },
      {
        label: "C",
        text: "The packages weigh about ten pounds each.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about whether the pickup happened. (A) confirms it directly. (B) is a sound-alike trap reusing 'picked up' to mean 'took up a hobby' instead of confirming the courier's visit, and (C) is an unrelated fact about weight rather than a yes/no answer.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The elevator maintenance is scheduled for this weekend, isn\'t it?"',
    options: [
      {
        label: "A",
        text: "The building has three elevators.",
      },
      {
        label: "B",
        text: "Maintenance crews usually work efficiently.",
      },
      {
        label: "C",
        text: "Yes, technicians are coming Saturday morning.",
      },
    ],
    correct: "C",
    explanation:
      "This tag question expects a yes/no confirmation of the schedule. (C) confirms it directly. (A) is an unrelated fact about the number of elevators, and (B) is a vague, general non-sequitur about crews rather than a confirmation.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Should we hold the client dinner at the steakhouse or the seafood restaurant?"',
    options: [
      {
        label: "A",
        text: "Yes, the client will enjoy either one.",
      },
      {
        label: "B",
        text: "The seafood restaurant has better reviews, so let's book that one.",
      },
      {
        label: "C",
        text: "The steakhouse just renovated its dining room.",
      },
    ],
    correct: "B",
    explanation:
      "This is an 'or' choice question requiring one of the two named options. (B) selects the seafood restaurant with a reason. (A) incorrectly answers with a plain yes/no, which doesn't fit an 'or' question, and (C) reuses 'steakhouse' but gives an unrelated renovation fact instead of making a choice.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The keynote speaker just canceled for tomorrow\'s conference."',
    options: [
      {
        label: "A",
        text: "Conferences usually run for two full days.",
      },
      {
        label: "B",
        text: "The keynote address covers digital marketing trends.",
      },
      {
        label: "C",
        text: "I'll reach out to our backup speaker right away.",
      },
    ],
    correct: "C",
    explanation:
      "This statement about a last-minute problem calls for an appropriate reaction. (C) proposes a logical next step. (A) is an unrelated fact about conference length, and (B) reuses 'keynote' but describes its topic instead of reacting to the cancellation.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Who reserved the demonstration kitchen for Thursday\'s cooking class?"',
    options: [
      {
        label: "A",
        text: "Ask Marie — she handles all the room bookings.",
      },
      {
        label: "B",
        text: "The kitchen was deep-cleaned on Monday.",
      },
      {
        label: "C",
        text: "Thursday's class is fully enrolled.",
      },
    ],
    correct: "A",
    explanation:
      "'Who' asks for a person, and (A) answers indirectly by pointing to the person who would know — a very common correct pattern in Part 2. (B) reuses 'kitchen' but describes cleaning, not who booked it, and (C) reuses 'Thursday' to state enrollment, another echo trap that never names anyone.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "When will the ferry schedule for the summer season be posted?"',
    options: [
      {
        label: "A",
        text: "The ferry holds about ninety passengers.",
      },
      {
        label: "B",
        text: "It hasn't been finalized yet — probably sometime next week.",
      },
      {
        label: "C",
        text: "I posted the letter on my way in.",
      },
    ],
    correct: "B",
    explanation:
      "'When' asks for a time, and (B) answers honestly with an approximate one — 'I don't know yet, but probably...' is a perfectly valid Part 2 response. (A) reuses 'ferry' but answers 'how many,' and (C) is a sound-alike trap using 'posted' to mean mailing a letter rather than publishing the schedule.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Where can I find the sign-up sheet for the charity fun run?"',
    options: [
      {
        label: "A",
        text: "The run is five kilometers this year.",
      },
      {
        label: "B",
        text: "It's pinned to the notice board in the break room.",
      },
      {
        label: "C",
        text: "You should sign the card for Tom's birthday.",
      },
    ],
    correct: "B",
    explanation:
      "'Where' asks for a location. (B) gives one. (A) reuses 'run' but answers 'how far,' a wrong question type, and (C) is a sound-alike trap swapping 'sign-up' for 'sign the card' — related sounds, unrelated topic.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why is the west staircase closed off this week?"',
    options: [
      {
        label: "A",
        text: "They're replacing the handrails on every floor.",
      },
      {
        label: "B",
        text: "The staircase has forty-eight steps.",
      },
      {
        label: "C",
        text: "It usually closes at nine p.m.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason, and replacing the handrails explains the closure. (B) reuses 'staircase' but states an irrelevant fact about the number of steps, and (C) reuses 'close' to describe daily hours rather than giving a reason for this week's closure.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Did the florist confirm the centerpiece order for the awards banquet?"',
    options: [
      {
        label: "A",
        text: "Yes, she called this morning — everything's on track.",
      },
      {
        label: "B",
        text: "The banquet hall seats three hundred.",
      },
      {
        label: "C",
        text: "I ordered the salmon, not the chicken.",
      },
    ],
    correct: "A",
    explanation:
      "This is a yes/no question about a confirmation. (A) confirms it directly. (B) reuses 'banquet' but answers a capacity question nobody asked, and (C) is a sound-alike trap reusing 'ordered' to describe a meal choice instead of the flower order.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The window washers are coming on Wednesday, aren\'t they?"',
    options: [
      {
        label: "A",
        text: "The windows on the fifth floor are the dirtiest.",
      },
      {
        label: "B",
        text: "Actually, they rescheduled to Friday because of the wind.",
      },
      {
        label: "C",
        text: "I washed my car over the weekend.",
      },
    ],
    correct: "B",
    explanation:
      "Tag questions expect confirmation — or a correction, which is what (B) gives: 'actually, the plan changed' is a classic correct Part 2 pattern. (A) reuses 'windows' without addressing the schedule, and (C) is a sound-alike trap moving 'washed' to an unrelated personal chore.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Isn\'t the dental clinic supposed to send a reminder before appointments?"',
    options: [
      {
        label: "A",
        text: "Yes, you should get a text two days beforehand.",
      },
      {
        label: "B",
        text: "The clinic added two new hygienists.",
      },
      {
        label: "C",
        text: "That reminds me of my trip to Lisbon.",
      },
    ],
    correct: "A",
    explanation:
      "Negative questions like 'Isn't...' still expect a yes/no answer, and (A) confirms the policy with a detail. (B) is an unrelated fact about staffing, and (C) is a sound-alike trap playing on 'reminder' with 'that reminds me' — familiar words, no answer.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Should we ship the trade samples by air, or is ground delivery fast enough?"',
    options: [
      {
        label: "A",
        text: "Whichever is cheaper — the client doesn't need them until next month.",
      },
      {
        label: "B",
        text: "Yes, the samples arrived in perfect condition.",
      },
      {
        label: "C",
        text: "The airport is about an hour from here.",
      },
    ],
    correct: "A",
    explanation:
      "Or-choice questions are usually answered by picking a side — but 'either one, based on cost' is also a natural, correct response, and that's what (A) gives. (B) treats it as a yes/no question, which doesn't fit an 'or' question, and (C) reuses the idea of 'air' with an irrelevant fact about the airport's distance.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context:
      'Question: "Do you want the lobby mural painted in warm tones or cooler blues and greens?"',
    options: [
      {
        label: "A",
        text: "The painter studied in Florence.",
      },
      {
        label: "B",
        text: "Warm tones — they'll match the wood paneling.",
      },
      {
        label: "C",
        text: "Yes, the lobby definitely needs something.",
      },
    ],
    correct: "B",
    explanation:
      "This 'or' choice question asks for one of two color directions. (B) picks warm tones and gives a reason. (A) is an unrelated fact about the painter's background, and (C) incorrectly answers with a plain yes/no, which doesn't work for an 'or' question.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Do you know how often the fire extinguishers need to be inspected?"',
    options: [
      {
        label: "A",
        text: "Yes, I know the fire marshal personally.",
      },
      {
        label: "B",
        text: "Once a year, according to the safety manual.",
      },
      {
        label: "C",
        text: "The extinguisher is mounted by the exit.",
      },
    ],
    correct: "B",
    explanation:
      "This is an embedded question — the real question is 'how often are they inspected?' (B) gives the frequency. (A) mistakes 'Do you know' for a literal yes/no question about acquaintance, and (C) answers 'where' the extinguisher is, a wrong question type.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "The translation agency needs two more days to finish the user manual."',
    options: [
      {
        label: "A",
        text: "Then let's push the product launch briefing to Thursday.",
      },
      {
        label: "B",
        text: "The manual is written in four languages.",
      },
      {
        label: "C",
        text: "I finished my coffee two minutes ago.",
      },
    ],
    correct: "A",
    explanation:
      "This statement about a delay calls for an appropriate reaction, and (A) adjusts the plan accordingly. (B) reuses 'manual' but states a fact instead of reacting to the delay, and (C) is a sound-alike trap echoing 'finish' and 'two' in a completely unrelated sentence.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the statement.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Statement and responses",
      durationSec: 0,
    },
    context: 'Statement: "I can\'t get the label printer to connect to my laptop."',
    options: [
      {
        label: "A",
        text: "Labels come in rolls of five hundred.",
      },
      {
        label: "B",
        text: "My laptop bag has a broken zipper too.",
      },
      {
        label: "C",
        text: "Try restarting it — that usually fixes the connection.",
      },
    ],
    correct: "C",
    explanation:
      "This statement describes a problem and calls for help or a suggestion, which (C) provides. (A) reuses 'labels' with an irrelevant supply fact, and (B) echoes 'laptop' but responds to a complaint that was never made — sympathy about the wrong thing.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How long does the guided tour of the botanical garden last?"',
    options: [
      {
        label: "A",
        text: "Roughly ninety minutes, including the greenhouse.",
      },
      {
        label: "B",
        text: "Tours leave from the main gate.",
      },
      {
        label: "C",
        text: "The garden was founded in 1902.",
      },
    ],
    correct: "A",
    explanation:
      "'How long' asks for a duration, and (A) gives one. (B) answers 'where' the tours start, a wrong question type, and (C) reuses 'garden' but gives its founding date — a 'when' fact that doesn't state the tour's length.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Could you give me a hand rearranging the display shelves before we open?"',
    options: [
      {
        label: "A",
        text: "Sure, just let me put my bag in the back first.",
      },
      {
        label: "B",
        text: "The shelves were delivered last Tuesday.",
      },
      {
        label: "C",
        text: "I gave him a gift card for his birthday.",
      },
    ],
    correct: "A",
    explanation:
      "'Could you...' is a request, so the natural response accepts or declines — (A) accepts. (B) reuses 'shelves' but states a delivery fact instead of responding to the request, and (C) is a sound-alike trap twisting 'give me a hand' into 'gave him a gift.'",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Where did you put the shipping labels?"',
    options: [
      {
        label: "A",
        text: "They're in the top drawer.",
      },
      {
        label: "B",
        text: "Around three o'clock.",
      },
      {
        label: "C",
        text: "No, I didn't ship it yet.",
      },
    ],
    correct: "A",
    explanation:
      "'Where' asks for a place. 'In the top drawer' names a location. (B) answers a 'when' question, and (C) is a yes/no answer that repeats the sound of 'shipping' — a classic word-repeat trap.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Have you finished reviewing the budget proposal?"',
    options: [
      {
        label: "A",
        text: "The finance team, I think.",
      },
      {
        label: "B",
        text: "Not quite, I need another hour.",
      },
      {
        label: "C",
        text: "It was a very productive review.",
      },
    ],
    correct: "B",
    explanation:
      "This yes/no question asks whether the task is done. 'Not quite, I need another hour' directly answers the status. (A) answers a 'who' question, and (C) repeats 'review' but comments on a meeting rather than saying whether the work is finished.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Would you like to schedule the call for Monday or Tuesday?"',
    options: [
      {
        label: "A",
        text: "Tuesday works better for me.",
      },
      {
        label: "B",
        text: "Yes, I'd like that.",
      },
      {
        label: "C",
        text: "In the main office.",
      },
    ],
    correct: "A",
    explanation:
      "This is a choice question offering two options, so a good reply picks one. 'Tuesday works better' selects an option. (B) is a yes/no reply, which cannot answer an either/or question, and (C) answers 'where'.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Could you send me the updated floor plan before noon?"',
    options: [
      {
        label: "A",
        text: "On the second floor.",
      },
      {
        label: "B",
        text: "Sure, I'll email it right away.",
      },
      {
        label: "C",
        text: "It's a beautiful plan.",
      },
    ],
    correct: "B",
    explanation:
      "This is a polite request for action. 'Sure, I'll email it right away' agrees and states how it will be done. (A) repeats 'floor' but answers a location question, and (C) repeats 'plan' but only gives an opinion instead of agreeing to send it.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "The printer on the third floor is out of toner again."',
    options: [
      {
        label: "A",
        text: "I'll order a new cartridge today.",
      },
      {
        label: "B",
        text: "Yes, please print two copies.",
      },
      {
        label: "C",
        text: "It cost about fifty dollars.",
      },
    ],
    correct: "A",
    explanation:
      "This is a statement reporting a problem; a natural reply offers to fix it. 'I'll order a new cartridge today' addresses the issue. (B) misreads it as a printing request, and (C) answers a 'how much' question that was never asked.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: "Question: \"You're joining the training session tomorrow, aren't you?\"",
    options: [
      {
        label: "A",
        text: "In the training room downstairs.",
      },
      {
        label: "B",
        text: "Yes, I signed up last week.",
      },
      {
        label: "C",
        text: "The trainer was excellent.",
      },
    ],
    correct: "B",
    explanation:
      "This tag question checks an expectation and calls for confirmation. 'Yes, I signed up last week' confirms attendance. (A) repeats 'training' but answers 'where', and (C) also repeats 'train-' but comments on a past session rather than confirming tomorrow's.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "Why was the client meeting postponed?"',
    options: [
      {
        label: "A",
        text: "Because the director had a scheduling conflict.",
      },
      {
        label: "B",
        text: "In meeting room B.",
      },
      {
        label: "C",
        text: "Yes, they postponed it.",
      },
    ],
    correct: "A",
    explanation:
      "'Why' asks for a reason. 'Because the director had a scheduling conflict' gives one. (B) answers 'where', and (C) is a yes/no answer that just repeats 'postponed' without explaining the reason.",
  },
  {
    prompt: "Part 2 · Question–Response. Choose the best reply to the question.",
    listening: true,
    spokenOptions: true,
    audio: {
      label: "Question and responses",
      durationSec: 0,
    },
    context: 'Question: "How long will the software installation take?"',
    options: [
      {
        label: "A",
        text: "In the IT department.",
      },
      {
        label: "B",
        text: "About forty-five minutes.",
      },
      {
        label: "C",
        text: "Yes, it's already installed.",
      },
    ],
    correct: "B",
    explanation:
      "'How long' asks for a duration. 'About forty-five minutes' gives a length of time. (A) answers 'where', and (C) is a yes/no answer that repeats 'install' and contradicts the question, which assumes the work has not yet been done.",
  },
];

export default questions;
