/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as SpeakingWritingRouteImport } from './routes/speaking-writing'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ListeningReadingRouteImport } from './routes/listening-reading'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyTipsIndexRouteImport } from './routes/study-tips.index'
import { Route as StudyTipsSlugRouteImport } from './routes/study-tips.$slug'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingWritingRoute = SpeakingWritingRouteImport.update({
  id: '/speaking-writing',
  path: '/speaking-writing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningReadingRoute = ListeningReadingRouteImport.update({
  id: '/listening-reading',
  path: '/listening-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyTipsIndexRoute = StudyTipsIndexRouteImport.update({
  id: '/study-tips/',
  path: '/study-tips/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyTipsSlugRoute = StudyTipsSlugRouteImport.update({
  id: '/study-tips/$slug',
  path: '/study-tips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking-writing': typeof SpeakingWritingRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips/': typeof StudyTipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking-writing': typeof SpeakingWritingRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips': typeof StudyTipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking-writing': typeof SpeakingWritingRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips/': typeof StudyTipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/listening-reading'
    | '/sitemap.xml'
    | '/speaking-writing'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/listening-reading'
    | '/sitemap.xml'
    | '/speaking-writing'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips'
  id:
    | '__root__'
    | '/'
    | '/listening-reading'
    | '/sitemap.xml'
    | '/speaking-writing'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListeningReadingRoute: typeof ListeningReadingRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingWritingRoute: typeof SpeakingWritingRoute
  VocabularyRoute: typeof VocabularyRoute
  StudyTipsSlugRoute: typeof StudyTipsSlugRoute
  StudyTipsIndexRoute: typeof StudyTipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking-writing': {
      id: '/speaking-writing'
      path: '/speaking-writing'
      fullPath: '/speaking-writing'
      preLoaderRoute: typeof SpeakingWritingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-reading': {
      id: '/listening-reading'
      path: '/listening-reading'
      fullPath: '/listening-reading'
      preLoaderRoute: typeof ListeningReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-tips/': {
      id: '/study-tips/'
      path: '/study-tips'
      fullPath: '/study-tips/'
      preLoaderRoute: typeof StudyTipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-tips/$slug': {
      id: '/study-tips/$slug'
      path: '/study-tips/$slug'
      fullPath: '/study-tips/$slug'
      preLoaderRoute: typeof StudyTipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListeningReadingRoute: ListeningReadingRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingWritingRoute: SpeakingWritingRoute,
  VocabularyRoute: VocabularyRoute,
  StudyTipsSlugRoute: StudyTipsSlugRoute,
  StudyTipsIndexRoute: StudyTipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
