/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VocabularyRouteImport } from './routes/vocabulary'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MockTestRouteImport } from './routes/mock-test'
import { Route as ListeningReadingRouteImport } from './routes/listening-reading'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as FourSkillsRouteImport } from './routes/four-skills'
import { Route as AdaptivePracticeRouteImport } from './routes/adaptive-practice'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudyTipsIndexRouteImport } from './routes/study-tips.index'
import { Route as StudyTipsSlugRouteImport } from './routes/study-tips.$slug'

const VocabularyRoute = VocabularyRouteImport.update({
  id: '/vocabulary',
  path: '/vocabulary',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MockTestRoute = MockTestRouteImport.update({
  id: '/mock-test',
  path: '/mock-test',
  getParentRoute: () => rootRouteImport,
} as any)
const ListeningReadingRoute = ListeningReadingRouteImport.update({
  id: '/listening-reading',
  path: '/listening-reading',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const FourSkillsRoute = FourSkillsRouteImport.update({
  id: '/four-skills',
  path: '/four-skills',
  getParentRoute: () => rootRouteImport,
} as any)
const AdaptivePracticeRoute = AdaptivePracticeRouteImport.update({
  id: '/adaptive-practice',
  path: '/adaptive-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyTipsIndexRoute = StudyTipsIndexRouteImport.update({
  id: '/study-tips/',
  path: '/study-tips/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyTipsSlugRoute = StudyTipsSlugRouteImport.update({
  id: '/study-tips/$slug',
  path: '/study-tips/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adaptive-practice': typeof AdaptivePracticeRoute
  '/four-skills': typeof FourSkillsRoute
  '/legal': typeof LegalRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/mock-test': typeof MockTestRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips/': typeof StudyTipsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adaptive-practice': typeof AdaptivePracticeRoute
  '/four-skills': typeof FourSkillsRoute
  '/legal': typeof LegalRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/mock-test': typeof MockTestRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips': typeof StudyTipsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adaptive-practice': typeof AdaptivePracticeRoute
  '/four-skills': typeof FourSkillsRoute
  '/legal': typeof LegalRoute
  '/listening-reading': typeof ListeningReadingRoute
  '/mock-test': typeof MockTestRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/progress': typeof ProgressRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/vocabulary': typeof VocabularyRoute
  '/study-tips/$slug': typeof StudyTipsSlugRoute
  '/study-tips/': typeof StudyTipsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adaptive-practice'
    | '/four-skills'
    | '/legal'
    | '/listening-reading'
    | '/mock-test'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/sitemap.xml'
    | '/terms'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adaptive-practice'
    | '/four-skills'
    | '/legal'
    | '/listening-reading'
    | '/mock-test'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/sitemap.xml'
    | '/terms'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips'
  id:
    | '__root__'
    | '/'
    | '/adaptive-practice'
    | '/four-skills'
    | '/legal'
    | '/listening-reading'
    | '/mock-test'
    | '/pricing'
    | '/privacy'
    | '/progress'
    | '/sitemap.xml'
    | '/terms'
    | '/vocabulary'
    | '/study-tips/$slug'
    | '/study-tips/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdaptivePracticeRoute: typeof AdaptivePracticeRoute
  FourSkillsRoute: typeof FourSkillsRoute
  LegalRoute: typeof LegalRoute
  ListeningReadingRoute: typeof ListeningReadingRoute
  MockTestRoute: typeof MockTestRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ProgressRoute: typeof ProgressRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  VocabularyRoute: typeof VocabularyRoute
  StudyTipsSlugRoute: typeof StudyTipsSlugRoute
  StudyTipsIndexRoute: typeof StudyTipsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vocabulary': {
      id: '/vocabulary'
      path: '/vocabulary'
      fullPath: '/vocabulary'
      preLoaderRoute: typeof VocabularyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mock-test': {
      id: '/mock-test'
      path: '/mock-test'
      fullPath: '/mock-test'
      preLoaderRoute: typeof MockTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listening-reading': {
      id: '/listening-reading'
      path: '/listening-reading'
      fullPath: '/listening-reading'
      preLoaderRoute: typeof ListeningReadingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/four-skills': {
      id: '/four-skills'
      path: '/four-skills'
      fullPath: '/four-skills'
      preLoaderRoute: typeof FourSkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adaptive-practice': {
      id: '/adaptive-practice'
      path: '/adaptive-practice'
      fullPath: '/adaptive-practice'
      preLoaderRoute: typeof AdaptivePracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-tips/': {
      id: '/study-tips/'
      path: '/study-tips'
      fullPath: '/study-tips/'
      preLoaderRoute: typeof StudyTipsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study-tips/$slug': {
      id: '/study-tips/$slug'
      path: '/study-tips/$slug'
      fullPath: '/study-tips/$slug'
      preLoaderRoute: typeof StudyTipsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdaptivePracticeRoute: AdaptivePracticeRoute,
  FourSkillsRoute: FourSkillsRoute,
  LegalRoute: LegalRoute,
  ListeningReadingRoute: ListeningReadingRoute,
  MockTestRoute: MockTestRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ProgressRoute: ProgressRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  VocabularyRoute: VocabularyRoute,
  StudyTipsSlugRoute: StudyTipsSlugRoute,
  StudyTipsIndexRoute: StudyTipsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
