// Generated by scripts/generate-audio.ts — do not edit by hand.
// Run `bun run generate:audio` (with OPENAI_API_KEY set) to regenerate.

export interface AudioManifestSegment {
  voice: string;
  file: string;
}

export interface AudioManifestEntry {
  model: string;
  segments: AudioManifestSegment[];
}

export const audioManifest: Record<string, AudioManifestEntry> = {
  "3joxdnis5v": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "3joxdnis5v-0.mp3",
      },
    ],
  },
  "14k2o3w46f0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "14k2o3w46f0-0.mp3",
      },
    ],
  },
  zwloofh3xd: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "zwloofh3xd-0.mp3",
      },
    ],
  },
  "1bm1kcj23a2": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1bm1kcj23a2-0.mp3",
      },
    ],
  },
  "24u6ykulwir": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "24u6ykulwir-0.mp3",
      },
    ],
  },
  "1wkpl1efrkq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1wkpl1efrkq-0.mp3",
      },
    ],
  },
  "1vs1cr0roh5": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1vs1cr0roh5-0.mp3",
      },
    ],
  },
  "2euravpd2aq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "2euravpd2aq-0.mp3",
      },
    ],
  },
  ofwo82pe67: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "ofwo82pe67-0.mp3",
      },
    ],
  },
  pcq2deu8ey: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "pcq2deu8ey-0.mp3",
      },
    ],
  },
  "1xzesxyofd9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1xzesxyofd9-0.mp3",
      },
    ],
  },
  n70njcp8nw: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "n70njcp8nw-0.mp3",
      },
    ],
  },
  "1llyz3n7v16": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1llyz3n7v16-0.mp3",
      },
    ],
  },
  "11o841zuh0c": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "11o841zuh0c-0.mp3",
      },
    ],
  },
  "13e9tbw4vt3": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "13e9tbw4vt3-0.mp3",
      },
    ],
  },
  "1m3vyv6fqep": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1m3vyv6fqep-0.mp3",
      },
    ],
  },
  l8ocxyis31: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "l8ocxyis31-0.mp3",
      },
    ],
  },
  "1qldo6j5zi": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1qldo6j5zi-0.mp3",
      },
    ],
  },
  nzb5jdotql: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "nzb5jdotql-0.mp3",
      },
    ],
  },
  jdj9x5y6vf: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "jdj9x5y6vf-0.mp3",
      },
    ],
  },
  "1ae8ttcoxag": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1ae8ttcoxag-0.mp3",
      },
    ],
  },
  "1x82i9psi9q": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1x82i9psi9q-0.mp3",
      },
    ],
  },
  "1eft6joyzyw": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1eft6joyzyw-0.mp3",
      },
    ],
  },
  t3a8ww2ea9: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "t3a8ww2ea9-0.mp3",
      },
    ],
  },
  "1qv40bhmxun": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1qv40bhmxun-0.mp3",
      },
    ],
  },
  "1m6n6pojrqa": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1m6n6pojrqa-0.mp3",
      },
    ],
  },
  "2fq7kzhh46g": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2fq7kzhh46g-0.mp3",
      },
    ],
  },
  "24ncbse2fad": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "24ncbse2fad-0.mp3",
      },
    ],
  },
  "12mxyh18sm4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "12mxyh18sm4-0.mp3",
      },
    ],
  },
  "1eq3csgxl28": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1eq3csgxl28-0.mp3",
      },
    ],
  },
  "15s70n1di0q": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "15s70n1di0q-0.mp3",
      },
    ],
  },
  "21d360u5as2": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "21d360u5as2-0.mp3",
      },
    ],
  },
  "1n5298e049d": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1n5298e049d-0.mp3",
      },
    ],
  },
  popimizltg: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "popimizltg-0.mp3",
      },
    ],
  },
  "1t95e9k33tf": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1t95e9k33tf-0.mp3",
      },
    ],
  },
  "12art5f8c9e": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "12art5f8c9e-0.mp3",
      },
    ],
  },
  hx2qctdwo6: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "hx2qctdwo6-0.mp3",
      },
    ],
  },
  "1gdmancnmcz": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1gdmancnmcz-0.mp3",
      },
    ],
  },
  "2p30itrj05": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2p30itrj05-0.mp3",
      },
    ],
  },
  "12t0uw6nzip": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "12t0uw6nzip-0.mp3",
      },
    ],
  },
  "1oh4g9o5ptb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1oh4g9o5ptb-0.mp3",
      },
    ],
  },
  bqvsg5s7sf: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "bqvsg5s7sf-0.mp3",
      },
    ],
  },
  "11kke62w8l6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "11kke62w8l6-0.mp3",
      },
    ],
  },
  "1gxavnr5792": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1gxavnr5792-0.mp3",
      },
    ],
  },
  "1ud9dpbarix": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1ud9dpbarix-0.mp3",
      },
    ],
  },
  "1ll8pjo8gk8": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1ll8pjo8gk8-0.mp3",
      },
    ],
  },
  "2aa2t1o9nij": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2aa2t1o9nij-0.mp3",
      },
    ],
  },
  q1joyumow: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "q1joyumow-0.mp3",
      },
    ],
  },
  "1dz6bi06e9z": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1dz6bi06e9z-0.mp3",
      },
    ],
  },
  "170s8vj85j9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "170s8vj85j9-0.mp3",
      },
    ],
  },
  "2951arlkg9u": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2951arlkg9u-0.mp3",
      },
    ],
  },
  "1wvlh87grkd": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1wvlh87grkd-0.mp3",
      },
    ],
  },
  "2deq94odqn": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2deq94odqn-0.mp3",
      },
    ],
  },
  "2b9km3ue9zs": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2b9km3ue9zs-0.mp3",
      },
    ],
  },
  np7mkbtdab: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "np7mkbtdab-0.mp3",
      },
    ],
  },
  "7jkphw9d8c": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "7jkphw9d8c-0.mp3",
      },
    ],
  },
  "1y4wujsjpru": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1y4wujsjpru-0.mp3",
      },
    ],
  },
  "286ohrmhsbt": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "286ohrmhsbt-0.mp3",
      },
    ],
  },
  "5bu5aw8exz": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "5bu5aw8exz-0.mp3",
      },
    ],
  },
  "2azhezzendi": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "2azhezzendi-0.mp3",
      },
    ],
  },
  "14os2c027ww": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "14os2c027ww-0.mp3",
      },
    ],
  },
  "1tv285n5gqs": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1tv285n5gqs-0.mp3",
      },
    ],
  },
  gkm7f1ldns: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "gkm7f1ldns-0.mp3",
      },
    ],
  },
  "29fwqarujq6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "29fwqarujq6-0.mp3",
      },
    ],
  },
  dmu0pd982s: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "dmu0pd982s-0.mp3",
      },
    ],
  },
  "21aobvmg2yd": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "21aobvmg2yd-0.mp3",
      },
    ],
  },
  gczqxgh8wr: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "gczqxgh8wr-0.mp3",
      },
    ],
  },
  "27mnyooz6ce": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "27mnyooz6ce-0.mp3",
      },
    ],
  },
  "12dmi1n9og2": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "12dmi1n9og2-0.mp3",
      },
    ],
  },
  jq78lj95ln: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "jq78lj95ln-0.mp3",
      },
    ],
  },
  "1p8vvt6yz6o": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1p8vvt6yz6o-0.mp3",
      },
    ],
  },
  "1n2tb3fa442": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1n2tb3fa442-0.mp3",
      },
    ],
  },
  t15loqwpc9: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "t15loqwpc9-0.mp3",
      },
    ],
  },
  "7iv02p5qbk": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "7iv02p5qbk-0.mp3",
      },
    ],
  },
  xqps15gtu8: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "xqps15gtu8-0.mp3",
      },
    ],
  },
  "27wdj5xs94u": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "27wdj5xs94u-0.mp3",
      },
    ],
  },
  "1ekr83g29lg": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1ekr83g29lg-0.mp3",
      },
    ],
  },
  m79u8fr6ap: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "m79u8fr6ap-0.mp3",
      },
    ],
  },
  z7z4agux6f: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "z7z4agux6f-0.mp3",
      },
    ],
  },
  "1c8ar1j4vk8": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1c8ar1j4vk8-0.mp3",
      },
    ],
  },
  "28wlwwc2jf9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "28wlwwc2jf9-0.mp3",
      },
    ],
  },
  "1nbjtfept3r": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1nbjtfept3r-0.mp3",
      },
    ],
  },
  "18m5dj4tffu": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "18m5dj4tffu-0.mp3",
      },
    ],
  },
  ioe9bgb7nl: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "ioe9bgb7nl-0.mp3",
      },
    ],
  },
  "128ntbe271h": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "128ntbe271h-0.mp3",
      },
    ],
  },
  "9hd2ugcdur": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "9hd2ugcdur-0.mp3",
      },
    ],
  },
  "28d4epxrdzs": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "28d4epxrdzs-0.mp3",
      },
    ],
  },
  "1gm9voc6p87": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1gm9voc6p87-0.mp3",
      },
    ],
  },
  rxm6jdr4rd: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "rxm6jdr4rd-0.mp3",
      },
    ],
  },
  "1ubhkrj2ecx": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1ubhkrj2ecx-0.mp3",
      },
    ],
  },
  "8r33gkir5f": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "8r33gkir5f-0.mp3",
      },
    ],
  },
  "2aa7jhcf98o": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "2aa7jhcf98o-0.mp3",
      },
    ],
  },
  "1zm22yepnau": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1zm22yepnau-0.mp3",
      },
    ],
  },
  tl522d8per: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "tl522d8per-0.mp3",
      },
    ],
  },
  "1eme83tp5co": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1eme83tp5co-0.mp3",
      },
    ],
  },
  "29f75g1054j": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "29f75g1054j-0.mp3",
      },
    ],
  },
  g6xmkdqwu7: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "g6xmkdqwu7-0.mp3",
      },
    ],
  },
  "4oovzzgh45": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "4oovzzgh45-0.mp3",
      },
    ],
  },
  "1lyf9cb2glb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1lyf9cb2glb-0.mp3",
      },
    ],
  },
  "2gbmi560p7c": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "2gbmi560p7c-0.mp3",
      },
    ],
  },
  gke3yixq4k: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "gke3yixq4k-0.mp3",
      },
    ],
  },
  "1inc4qh6oe3": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1inc4qh6oe3-0.mp3",
      },
    ],
  },
  zfa40x1m4l: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "zfa40x1m4l-0.mp3",
      },
    ],
  },
  moyu7henzl: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "moyu7henzl-0.mp3",
      },
    ],
  },
  "1nfkptam3sm": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1nfkptam3sm-0.mp3",
      },
    ],
  },
  cp2y1tcis: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "cp2y1tcis-0.mp3",
      },
    ],
  },
  "2ezar0ynq3g": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2ezar0ynq3g-0.mp3",
      },
    ],
  },
  "1b05s2pyqw4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1b05s2pyqw4-0.mp3",
      },
    ],
  },
  "1pc7dthn5y": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1pc7dthn5y-0.mp3",
      },
    ],
  },
  "1wol6mzzl3s": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1wol6mzzl3s-0.mp3",
      },
    ],
  },
  "27mh2gt7nrq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "27mh2gt7nrq-0.mp3",
      },
    ],
  },
  rhar031dnh: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "rhar031dnh-0.mp3",
      },
    ],
  },
  "1kse10o8o04": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1kse10o8o04-0.mp3",
      },
    ],
  },
  "2h79hieylp": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2h79hieylp-0.mp3",
      },
    ],
  },
  eflv5vgye5: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "eflv5vgye5-0.mp3",
      },
    ],
  },
  ip00ecq9xs: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "ip00ecq9xs-0.mp3",
      },
    ],
  },
  i8ubqlw4zv: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "i8ubqlw4zv-0.mp3",
      },
    ],
  },
  j737yfurbh: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "j737yfurbh-0.mp3",
      },
    ],
  },
  "1ew43pzml7s": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1ew43pzml7s-0.mp3",
      },
    ],
  },
  "2d4ev0osi0g": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2d4ev0osi0g-0.mp3",
      },
      {
        voice: "onyx",
        file: "2d4ev0osi0g-1.mp3",
      },
      {
        voice: "nova",
        file: "2d4ev0osi0g-2.mp3",
      },
      {
        voice: "onyx",
        file: "2d4ev0osi0g-3.mp3",
      },
      {
        voice: "alloy",
        file: "2d4ev0osi0g-4.mp3",
      },
    ],
  },
  gzrnl94lly: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "gzrnl94lly-0.mp3",
      },
      {
        voice: "shimmer",
        file: "gzrnl94lly-1.mp3",
      },
      {
        voice: "alloy",
        file: "gzrnl94lly-2.mp3",
      },
      {
        voice: "shimmer",
        file: "gzrnl94lly-3.mp3",
      },
      {
        voice: "alloy",
        file: "gzrnl94lly-4.mp3",
      },
      {
        voice: "alloy",
        file: "gzrnl94lly-5.mp3",
      },
    ],
  },
  e2ilet4ofx: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "e2ilet4ofx-0.mp3",
      },
      {
        voice: "onyx",
        file: "e2ilet4ofx-1.mp3",
      },
      {
        voice: "nova",
        file: "e2ilet4ofx-2.mp3",
      },
      {
        voice: "onyx",
        file: "e2ilet4ofx-3.mp3",
      },
      {
        voice: "nova",
        file: "e2ilet4ofx-4.mp3",
      },
      {
        voice: "alloy",
        file: "e2ilet4ofx-5.mp3",
      },
    ],
  },
  "2e253q6r2qm": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2e253q6r2qm-0.mp3",
      },
      {
        voice: "shimmer",
        file: "2e253q6r2qm-1.mp3",
      },
      {
        voice: "alloy",
        file: "2e253q6r2qm-2.mp3",
      },
      {
        voice: "shimmer",
        file: "2e253q6r2qm-3.mp3",
      },
      {
        voice: "alloy",
        file: "2e253q6r2qm-4.mp3",
      },
    ],
  },
  vpypoh3ymv: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "vpypoh3ymv-0.mp3",
      },
      {
        voice: "nova",
        file: "vpypoh3ymv-1.mp3",
      },
      {
        voice: "onyx",
        file: "vpypoh3ymv-2.mp3",
      },
      {
        voice: "nova",
        file: "vpypoh3ymv-3.mp3",
      },
      {
        voice: "alloy",
        file: "vpypoh3ymv-4.mp3",
      },
    ],
  },
  "1ezxefokesw": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1ezxefokesw-0.mp3",
      },
      {
        voice: "alloy",
        file: "1ezxefokesw-1.mp3",
      },
      {
        voice: "shimmer",
        file: "1ezxefokesw-2.mp3",
      },
      {
        voice: "alloy",
        file: "1ezxefokesw-3.mp3",
      },
      {
        voice: "shimmer",
        file: "1ezxefokesw-4.mp3",
      },
      {
        voice: "alloy",
        file: "1ezxefokesw-5.mp3",
      },
    ],
  },
  "4jtj67cfdd": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "4jtj67cfdd-0.mp3",
      },
      {
        voice: "nova",
        file: "4jtj67cfdd-1.mp3",
      },
      {
        voice: "onyx",
        file: "4jtj67cfdd-2.mp3",
      },
      {
        voice: "nova",
        file: "4jtj67cfdd-3.mp3",
      },
      {
        voice: "alloy",
        file: "4jtj67cfdd-4.mp3",
      },
    ],
  },
  ukbsdzokwg: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "ukbsdzokwg-0.mp3",
      },
      {
        voice: "alloy",
        file: "ukbsdzokwg-1.mp3",
      },
      {
        voice: "shimmer",
        file: "ukbsdzokwg-2.mp3",
      },
      {
        voice: "alloy",
        file: "ukbsdzokwg-3.mp3",
      },
      {
        voice: "alloy",
        file: "ukbsdzokwg-4.mp3",
      },
    ],
  },
  "1pdaidw3cj6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1pdaidw3cj6-0.mp3",
      },
      {
        voice: "nova",
        file: "1pdaidw3cj6-1.mp3",
      },
      {
        voice: "onyx",
        file: "1pdaidw3cj6-2.mp3",
      },
      {
        voice: "nova",
        file: "1pdaidw3cj6-3.mp3",
      },
      {
        voice: "alloy",
        file: "1pdaidw3cj6-4.mp3",
      },
    ],
  },
  "1h3rwpg6a1l": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1h3rwpg6a1l-0.mp3",
      },
      {
        voice: "alloy",
        file: "1h3rwpg6a1l-1.mp3",
      },
      {
        voice: "shimmer",
        file: "1h3rwpg6a1l-2.mp3",
      },
      {
        voice: "alloy",
        file: "1h3rwpg6a1l-3.mp3",
      },
      {
        voice: "alloy",
        file: "1h3rwpg6a1l-4.mp3",
      },
    ],
  },
  wtqbu885fn: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "wtqbu885fn-0.mp3",
      },
      {
        voice: "nova",
        file: "wtqbu885fn-1.mp3",
      },
      {
        voice: "onyx",
        file: "wtqbu885fn-2.mp3",
      },
      {
        voice: "nova",
        file: "wtqbu885fn-3.mp3",
      },
      {
        voice: "alloy",
        file: "wtqbu885fn-4.mp3",
      },
    ],
  },
  yjnzg0ma26: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "yjnzg0ma26-0.mp3",
      },
      {
        voice: "alloy",
        file: "yjnzg0ma26-1.mp3",
      },
      {
        voice: "shimmer",
        file: "yjnzg0ma26-2.mp3",
      },
      {
        voice: "alloy",
        file: "yjnzg0ma26-3.mp3",
      },
      {
        voice: "alloy",
        file: "yjnzg0ma26-4.mp3",
      },
    ],
  },
  fxxgtvzxuv: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "fxxgtvzxuv-0.mp3",
      },
      {
        voice: "nova",
        file: "fxxgtvzxuv-1.mp3",
      },
      {
        voice: "onyx",
        file: "fxxgtvzxuv-2.mp3",
      },
      {
        voice: "nova",
        file: "fxxgtvzxuv-3.mp3",
      },
      {
        voice: "alloy",
        file: "fxxgtvzxuv-4.mp3",
      },
    ],
  },
  "12tgyqblegm": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "12tgyqblegm-0.mp3",
      },
      {
        voice: "alloy",
        file: "12tgyqblegm-1.mp3",
      },
      {
        voice: "shimmer",
        file: "12tgyqblegm-2.mp3",
      },
      {
        voice: "alloy",
        file: "12tgyqblegm-3.mp3",
      },
      {
        voice: "alloy",
        file: "12tgyqblegm-4.mp3",
      },
    ],
  },
  "26ou6fgoxtq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "26ou6fgoxtq-0.mp3",
      },
      {
        voice: "nova",
        file: "26ou6fgoxtq-1.mp3",
      },
      {
        voice: "onyx",
        file: "26ou6fgoxtq-2.mp3",
      },
      {
        voice: "nova",
        file: "26ou6fgoxtq-3.mp3",
      },
      {
        voice: "alloy",
        file: "26ou6fgoxtq-4.mp3",
      },
    ],
  },
  "1rvc5yycckm": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1rvc5yycckm-0.mp3",
      },
      {
        voice: "alloy",
        file: "1rvc5yycckm-1.mp3",
      },
      {
        voice: "shimmer",
        file: "1rvc5yycckm-2.mp3",
      },
      {
        voice: "alloy",
        file: "1rvc5yycckm-3.mp3",
      },
      {
        voice: "alloy",
        file: "1rvc5yycckm-4.mp3",
      },
    ],
  },
  "8349evm164": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "8349evm164-0.mp3",
      },
      {
        voice: "nova",
        file: "8349evm164-1.mp3",
      },
      {
        voice: "onyx",
        file: "8349evm164-2.mp3",
      },
      {
        voice: "nova",
        file: "8349evm164-3.mp3",
      },
      {
        voice: "onyx",
        file: "8349evm164-4.mp3",
      },
      {
        voice: "alloy",
        file: "8349evm164-5.mp3",
      },
    ],
  },
  "208oceh4x40": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "208oceh4x40-0.mp3",
      },
      {
        voice: "alloy",
        file: "208oceh4x40-1.mp3",
      },
      {
        voice: "shimmer",
        file: "208oceh4x40-2.mp3",
      },
      {
        voice: "alloy",
        file: "208oceh4x40-3.mp3",
      },
      {
        voice: "alloy",
        file: "208oceh4x40-4.mp3",
      },
    ],
  },
  "22c3urkys0f": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "22c3urkys0f-0.mp3",
      },
      {
        voice: "nova",
        file: "22c3urkys0f-1.mp3",
      },
      {
        voice: "onyx",
        file: "22c3urkys0f-2.mp3",
      },
      {
        voice: "nova",
        file: "22c3urkys0f-3.mp3",
      },
      {
        voice: "alloy",
        file: "22c3urkys0f-4.mp3",
      },
    ],
  },
  "2fmy8ur3k9p": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2fmy8ur3k9p-0.mp3",
      },
      {
        voice: "shimmer",
        file: "2fmy8ur3k9p-1.mp3",
      },
      {
        voice: "alloy",
        file: "2fmy8ur3k9p-2.mp3",
      },
      {
        voice: "shimmer",
        file: "2fmy8ur3k9p-3.mp3",
      },
      {
        voice: "alloy",
        file: "2fmy8ur3k9p-4.mp3",
      },
    ],
  },
  "1voyy4zf1jd": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1voyy4zf1jd-0.mp3",
      },
      {
        voice: "onyx",
        file: "1voyy4zf1jd-1.mp3",
      },
      {
        voice: "nova",
        file: "1voyy4zf1jd-2.mp3",
      },
      {
        voice: "onyx",
        file: "1voyy4zf1jd-3.mp3",
      },
      {
        voice: "alloy",
        file: "1voyy4zf1jd-4.mp3",
      },
    ],
  },
  qs79s8e5hk: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "qs79s8e5hk-0.mp3",
      },
      {
        voice: "shimmer",
        file: "qs79s8e5hk-1.mp3",
      },
      {
        voice: "alloy",
        file: "qs79s8e5hk-2.mp3",
      },
      {
        voice: "shimmer",
        file: "qs79s8e5hk-3.mp3",
      },
      {
        voice: "alloy",
        file: "qs79s8e5hk-4.mp3",
      },
    ],
  },
  "25oy0pdp4oz": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "25oy0pdp4oz-0.mp3",
      },
      {
        voice: "nova",
        file: "25oy0pdp4oz-1.mp3",
      },
      {
        voice: "onyx",
        file: "25oy0pdp4oz-2.mp3",
      },
      {
        voice: "nova",
        file: "25oy0pdp4oz-3.mp3",
      },
      {
        voice: "alloy",
        file: "25oy0pdp4oz-4.mp3",
      },
    ],
  },
  "17twzzalhed": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "17twzzalhed-0.mp3",
      },
      {
        voice: "shimmer",
        file: "17twzzalhed-1.mp3",
      },
      {
        voice: "alloy",
        file: "17twzzalhed-2.mp3",
      },
      {
        voice: "shimmer",
        file: "17twzzalhed-3.mp3",
      },
      {
        voice: "alloy",
        file: "17twzzalhed-4.mp3",
      },
    ],
  },
  "1xhjt4nm5ci": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1xhjt4nm5ci-0.mp3",
      },
      {
        voice: "onyx",
        file: "1xhjt4nm5ci-1.mp3",
      },
      {
        voice: "nova",
        file: "1xhjt4nm5ci-2.mp3",
      },
      {
        voice: "onyx",
        file: "1xhjt4nm5ci-3.mp3",
      },
      {
        voice: "alloy",
        file: "1xhjt4nm5ci-4.mp3",
      },
    ],
  },
  "2aucrb8qkeb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2aucrb8qkeb-0.mp3",
      },
      {
        voice: "shimmer",
        file: "2aucrb8qkeb-1.mp3",
      },
      {
        voice: "alloy",
        file: "2aucrb8qkeb-2.mp3",
      },
      {
        voice: "shimmer",
        file: "2aucrb8qkeb-3.mp3",
      },
      {
        voice: "alloy",
        file: "2aucrb8qkeb-4.mp3",
      },
    ],
  },
  "29uwudkvagm": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "29uwudkvagm-0.mp3",
      },
      {
        voice: "onyx",
        file: "29uwudkvagm-1.mp3",
      },
      {
        voice: "nova",
        file: "29uwudkvagm-2.mp3",
      },
      {
        voice: "onyx",
        file: "29uwudkvagm-3.mp3",
      },
      {
        voice: "alloy",
        file: "29uwudkvagm-4.mp3",
      },
    ],
  },
  "4yj9x477v": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "4yj9x477v-0.mp3",
      },
      {
        voice: "shimmer",
        file: "4yj9x477v-1.mp3",
      },
      {
        voice: "alloy",
        file: "4yj9x477v-2.mp3",
      },
      {
        voice: "shimmer",
        file: "4yj9x477v-3.mp3",
      },
      {
        voice: "alloy",
        file: "4yj9x477v-4.mp3",
      },
    ],
  },
  "25uo3prh4bq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "25uo3prh4bq-0.mp3",
      },
      {
        voice: "onyx",
        file: "25uo3prh4bq-1.mp3",
      },
      {
        voice: "nova",
        file: "25uo3prh4bq-2.mp3",
      },
      {
        voice: "onyx",
        file: "25uo3prh4bq-3.mp3",
      },
      {
        voice: "alloy",
        file: "25uo3prh4bq-4.mp3",
      },
    ],
  },
  "1r839l37uvg": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1r839l37uvg-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1r839l37uvg-1.mp3",
      },
      {
        voice: "alloy",
        file: "1r839l37uvg-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1r839l37uvg-3.mp3",
      },
      {
        voice: "alloy",
        file: "1r839l37uvg-4.mp3",
      },
    ],
  },
  "110ii3wr3f": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "110ii3wr3f-0.mp3",
      },
      {
        voice: "onyx",
        file: "110ii3wr3f-1.mp3",
      },
      {
        voice: "nova",
        file: "110ii3wr3f-2.mp3",
      },
      {
        voice: "onyx",
        file: "110ii3wr3f-3.mp3",
      },
      {
        voice: "alloy",
        file: "110ii3wr3f-4.mp3",
      },
    ],
  },
  "1nls3pcviao": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1nls3pcviao-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1nls3pcviao-1.mp3",
      },
      {
        voice: "alloy",
        file: "1nls3pcviao-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1nls3pcviao-3.mp3",
      },
      {
        voice: "alloy",
        file: "1nls3pcviao-4.mp3",
      },
    ],
  },
  "1e5kfetsac6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1e5kfetsac6-0.mp3",
      },
      {
        voice: "onyx",
        file: "1e5kfetsac6-1.mp3",
      },
      {
        voice: "nova",
        file: "1e5kfetsac6-2.mp3",
      },
      {
        voice: "onyx",
        file: "1e5kfetsac6-3.mp3",
      },
      {
        voice: "alloy",
        file: "1e5kfetsac6-4.mp3",
      },
    ],
  },
  "1k1n0znpthp": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1k1n0znpthp-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1k1n0znpthp-1.mp3",
      },
      {
        voice: "alloy",
        file: "1k1n0znpthp-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1k1n0znpthp-3.mp3",
      },
      {
        voice: "alloy",
        file: "1k1n0znpthp-4.mp3",
      },
    ],
  },
  mqgbty21u4: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "mqgbty21u4-0.mp3",
      },
      {
        voice: "onyx",
        file: "mqgbty21u4-1.mp3",
      },
      {
        voice: "nova",
        file: "mqgbty21u4-2.mp3",
      },
      {
        voice: "onyx",
        file: "mqgbty21u4-3.mp3",
      },
      {
        voice: "alloy",
        file: "mqgbty21u4-4.mp3",
      },
    ],
  },
  "23848jfkoob": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "23848jfkoob-0.mp3",
      },
      {
        voice: "shimmer",
        file: "23848jfkoob-1.mp3",
      },
      {
        voice: "alloy",
        file: "23848jfkoob-2.mp3",
      },
      {
        voice: "shimmer",
        file: "23848jfkoob-3.mp3",
      },
      {
        voice: "alloy",
        file: "23848jfkoob-4.mp3",
      },
    ],
  },
  rsym2n9rx2: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "rsym2n9rx2-0.mp3",
      },
      {
        voice: "onyx",
        file: "rsym2n9rx2-1.mp3",
      },
      {
        voice: "nova",
        file: "rsym2n9rx2-2.mp3",
      },
      {
        voice: "onyx",
        file: "rsym2n9rx2-3.mp3",
      },
      {
        voice: "alloy",
        file: "rsym2n9rx2-4.mp3",
      },
    ],
  },
  "8knjhht4g5": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "8knjhht4g5-0.mp3",
      },
      {
        voice: "shimmer",
        file: "8knjhht4g5-1.mp3",
      },
      {
        voice: "alloy",
        file: "8knjhht4g5-2.mp3",
      },
      {
        voice: "shimmer",
        file: "8knjhht4g5-3.mp3",
      },
      {
        voice: "alloy",
        file: "8knjhht4g5-4.mp3",
      },
    ],
  },
  "1s38um46ym1": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1s38um46ym1-0.mp3",
      },
      {
        voice: "onyx",
        file: "1s38um46ym1-1.mp3",
      },
      {
        voice: "nova",
        file: "1s38um46ym1-2.mp3",
      },
      {
        voice: "onyx",
        file: "1s38um46ym1-3.mp3",
      },
      {
        voice: "alloy",
        file: "1s38um46ym1-4.mp3",
      },
    ],
  },
  nnlx24lv7z: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "nnlx24lv7z-0.mp3",
      },
      {
        voice: "shimmer",
        file: "nnlx24lv7z-1.mp3",
      },
      {
        voice: "alloy",
        file: "nnlx24lv7z-2.mp3",
      },
      {
        voice: "shimmer",
        file: "nnlx24lv7z-3.mp3",
      },
      {
        voice: "alloy",
        file: "nnlx24lv7z-4.mp3",
      },
    ],
  },
  "1l9t1zvpd6q": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1l9t1zvpd6q-0.mp3",
      },
      {
        voice: "nova",
        file: "1l9t1zvpd6q-1.mp3",
      },
      {
        voice: "onyx",
        file: "1l9t1zvpd6q-2.mp3",
      },
      {
        voice: "nova",
        file: "1l9t1zvpd6q-3.mp3",
      },
      {
        voice: "alloy",
        file: "1l9t1zvpd6q-4.mp3",
      },
    ],
  },
  "14nqwf6ova3": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "14nqwf6ova3-0.mp3",
      },
      {
        voice: "alloy",
        file: "14nqwf6ova3-1.mp3",
      },
      {
        voice: "shimmer",
        file: "14nqwf6ova3-2.mp3",
      },
      {
        voice: "alloy",
        file: "14nqwf6ova3-3.mp3",
      },
      {
        voice: "alloy",
        file: "14nqwf6ova3-4.mp3",
      },
    ],
  },
  "1y06len7tdq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1y06len7tdq-0.mp3",
      },
      {
        voice: "nova",
        file: "1y06len7tdq-1.mp3",
      },
      {
        voice: "onyx",
        file: "1y06len7tdq-2.mp3",
      },
      {
        voice: "nova",
        file: "1y06len7tdq-3.mp3",
      },
      {
        voice: "alloy",
        file: "1y06len7tdq-4.mp3",
      },
    ],
  },
  "1xmp0y6heyg": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1xmp0y6heyg-0.mp3",
      },
      {
        voice: "alloy",
        file: "1xmp0y6heyg-1.mp3",
      },
      {
        voice: "shimmer",
        file: "1xmp0y6heyg-2.mp3",
      },
      {
        voice: "alloy",
        file: "1xmp0y6heyg-3.mp3",
      },
      {
        voice: "alloy",
        file: "1xmp0y6heyg-4.mp3",
      },
    ],
  },
  "2bbd2b0osm4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "2bbd2b0osm4-0.mp3",
      },
      {
        voice: "nova",
        file: "2bbd2b0osm4-1.mp3",
      },
      {
        voice: "onyx",
        file: "2bbd2b0osm4-2.mp3",
      },
      {
        voice: "nova",
        file: "2bbd2b0osm4-3.mp3",
      },
      {
        voice: "alloy",
        file: "2bbd2b0osm4-4.mp3",
      },
    ],
  },
  "2ejyaro7mvz": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2ejyaro7mvz-0.mp3",
      },
      {
        voice: "shimmer",
        file: "2ejyaro7mvz-1.mp3",
      },
      {
        voice: "alloy",
        file: "2ejyaro7mvz-2.mp3",
      },
      {
        voice: "shimmer",
        file: "2ejyaro7mvz-3.mp3",
      },
      {
        voice: "alloy",
        file: "2ejyaro7mvz-4.mp3",
      },
    ],
  },
  "1uxdjx8g68d": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1uxdjx8g68d-0.mp3",
      },
      {
        voice: "onyx",
        file: "1uxdjx8g68d-1.mp3",
      },
      {
        voice: "nova",
        file: "1uxdjx8g68d-2.mp3",
      },
      {
        voice: "onyx",
        file: "1uxdjx8g68d-3.mp3",
      },
      {
        voice: "alloy",
        file: "1uxdjx8g68d-4.mp3",
      },
    ],
  },
  "1zldxjakn5a": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1zldxjakn5a-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1zldxjakn5a-1.mp3",
      },
      {
        voice: "alloy",
        file: "1zldxjakn5a-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1zldxjakn5a-3.mp3",
      },
      {
        voice: "alloy",
        file: "1zldxjakn5a-4.mp3",
      },
    ],
  },
  "1rc65w2jcl4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1rc65w2jcl4-0.mp3",
      },
      {
        voice: "onyx",
        file: "1rc65w2jcl4-1.mp3",
      },
      {
        voice: "nova",
        file: "1rc65w2jcl4-2.mp3",
      },
      {
        voice: "onyx",
        file: "1rc65w2jcl4-3.mp3",
      },
      {
        voice: "alloy",
        file: "1rc65w2jcl4-4.mp3",
      },
    ],
  },
  zgg423fne6: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "zgg423fne6-0.mp3",
      },
      {
        voice: "shimmer",
        file: "zgg423fne6-1.mp3",
      },
      {
        voice: "alloy",
        file: "zgg423fne6-2.mp3",
      },
      {
        voice: "shimmer",
        file: "zgg423fne6-3.mp3",
      },
      {
        voice: "alloy",
        file: "zgg423fne6-4.mp3",
      },
    ],
  },
  "169f1cn6zng": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "169f1cn6zng-0.mp3",
      },
      {
        voice: "onyx",
        file: "169f1cn6zng-1.mp3",
      },
      {
        voice: "nova",
        file: "169f1cn6zng-2.mp3",
      },
      {
        voice: "onyx",
        file: "169f1cn6zng-3.mp3",
      },
      {
        voice: "alloy",
        file: "169f1cn6zng-4.mp3",
      },
    ],
  },
  dj5dvuym2p: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "dj5dvuym2p-0.mp3",
      },
      {
        voice: "shimmer",
        file: "dj5dvuym2p-1.mp3",
      },
      {
        voice: "alloy",
        file: "dj5dvuym2p-2.mp3",
      },
      {
        voice: "shimmer",
        file: "dj5dvuym2p-3.mp3",
      },
      {
        voice: "alloy",
        file: "dj5dvuym2p-4.mp3",
      },
    ],
  },
  "2ujwo7b1or": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2ujwo7b1or-0.mp3",
      },
      {
        voice: "onyx",
        file: "2ujwo7b1or-1.mp3",
      },
      {
        voice: "nova",
        file: "2ujwo7b1or-2.mp3",
      },
      {
        voice: "onyx",
        file: "2ujwo7b1or-3.mp3",
      },
      {
        voice: "alloy",
        file: "2ujwo7b1or-4.mp3",
      },
    ],
  },
  "89w1hcs54": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "89w1hcs54-0.mp3",
      },
      {
        voice: "shimmer",
        file: "89w1hcs54-1.mp3",
      },
      {
        voice: "alloy",
        file: "89w1hcs54-2.mp3",
      },
      {
        voice: "shimmer",
        file: "89w1hcs54-3.mp3",
      },
      {
        voice: "alloy",
        file: "89w1hcs54-4.mp3",
      },
    ],
  },
  "1rvzext133y": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1rvzext133y-0.mp3",
      },
      {
        voice: "nova",
        file: "1rvzext133y-1.mp3",
      },
      {
        voice: "onyx",
        file: "1rvzext133y-2.mp3",
      },
      {
        voice: "nova",
        file: "1rvzext133y-3.mp3",
      },
      {
        voice: "alloy",
        file: "1rvzext133y-4.mp3",
      },
    ],
  },
  "10kt4b23zwe": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "10kt4b23zwe-0.mp3",
      },
      {
        voice: "alloy",
        file: "10kt4b23zwe-1.mp3",
      },
      {
        voice: "shimmer",
        file: "10kt4b23zwe-2.mp3",
      },
      {
        voice: "alloy",
        file: "10kt4b23zwe-3.mp3",
      },
      {
        voice: "alloy",
        file: "10kt4b23zwe-4.mp3",
      },
    ],
  },
  "4lm57hquj9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "4lm57hquj9-0.mp3",
      },
      {
        voice: "nova",
        file: "4lm57hquj9-1.mp3",
      },
      {
        voice: "onyx",
        file: "4lm57hquj9-2.mp3",
      },
      {
        voice: "nova",
        file: "4lm57hquj9-3.mp3",
      },
      {
        voice: "alloy",
        file: "4lm57hquj9-4.mp3",
      },
    ],
  },
  expmppedt6: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "expmppedt6-0.mp3",
      },
      {
        voice: "alloy",
        file: "expmppedt6-1.mp3",
      },
      {
        voice: "shimmer",
        file: "expmppedt6-2.mp3",
      },
      {
        voice: "alloy",
        file: "expmppedt6-3.mp3",
      },
      {
        voice: "alloy",
        file: "expmppedt6-4.mp3",
      },
    ],
  },
  "1euxpq4jgpe": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1euxpq4jgpe-0.mp3",
      },
      {
        voice: "onyx",
        file: "1euxpq4jgpe-1.mp3",
      },
      {
        voice: "nova",
        file: "1euxpq4jgpe-2.mp3",
      },
      {
        voice: "onyx",
        file: "1euxpq4jgpe-3.mp3",
      },
      {
        voice: "alloy",
        file: "1euxpq4jgpe-4.mp3",
      },
    ],
  },
  "206o0urplut": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "206o0urplut-0.mp3",
      },
      {
        voice: "alloy",
        file: "206o0urplut-1.mp3",
      },
      {
        voice: "shimmer",
        file: "206o0urplut-2.mp3",
      },
      {
        voice: "alloy",
        file: "206o0urplut-3.mp3",
      },
      {
        voice: "alloy",
        file: "206o0urplut-4.mp3",
      },
    ],
  },
  "1mew5llmd11": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1mew5llmd11-0.mp3",
      },
      {
        voice: "onyx",
        file: "1mew5llmd11-1.mp3",
      },
      {
        voice: "nova",
        file: "1mew5llmd11-2.mp3",
      },
      {
        voice: "onyx",
        file: "1mew5llmd11-3.mp3",
      },
      {
        voice: "alloy",
        file: "1mew5llmd11-4.mp3",
      },
    ],
  },
  "1y75k18lru0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1y75k18lru0-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1y75k18lru0-1.mp3",
      },
      {
        voice: "alloy",
        file: "1y75k18lru0-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1y75k18lru0-3.mp3",
      },
      {
        voice: "alloy",
        file: "1y75k18lru0-4.mp3",
      },
    ],
  },
  "13fmitcwjgr": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "13fmitcwjgr-0.mp3",
      },
      {
        voice: "onyx",
        file: "13fmitcwjgr-1.mp3",
      },
      {
        voice: "nova",
        file: "13fmitcwjgr-2.mp3",
      },
      {
        voice: "onyx",
        file: "13fmitcwjgr-3.mp3",
      },
      {
        voice: "alloy",
        file: "13fmitcwjgr-4.mp3",
      },
    ],
  },
  pb2ouqjn9i: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "pb2ouqjn9i-0.mp3",
      },
      {
        voice: "shimmer",
        file: "pb2ouqjn9i-1.mp3",
      },
      {
        voice: "alloy",
        file: "pb2ouqjn9i-2.mp3",
      },
      {
        voice: "shimmer",
        file: "pb2ouqjn9i-3.mp3",
      },
      {
        voice: "alloy",
        file: "pb2ouqjn9i-4.mp3",
      },
    ],
  },
  "1mlwzup4iwq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1mlwzup4iwq-0.mp3",
      },
      {
        voice: "onyx",
        file: "1mlwzup4iwq-1.mp3",
      },
      {
        voice: "nova",
        file: "1mlwzup4iwq-2.mp3",
      },
      {
        voice: "onyx",
        file: "1mlwzup4iwq-3.mp3",
      },
      {
        voice: "alloy",
        file: "1mlwzup4iwq-4.mp3",
      },
    ],
  },
  "1wno71vsvcq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1wno71vsvcq-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1wno71vsvcq-1.mp3",
      },
      {
        voice: "alloy",
        file: "1wno71vsvcq-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1wno71vsvcq-3.mp3",
      },
      {
        voice: "alloy",
        file: "1wno71vsvcq-4.mp3",
      },
    ],
  },
  w1p3yfivf1: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "w1p3yfivf1-0.mp3",
      },
      {
        voice: "onyx",
        file: "w1p3yfivf1-1.mp3",
      },
      {
        voice: "nova",
        file: "w1p3yfivf1-2.mp3",
      },
      {
        voice: "onyx",
        file: "w1p3yfivf1-3.mp3",
      },
      {
        voice: "alloy",
        file: "w1p3yfivf1-4.mp3",
      },
    ],
  },
  "19s576wcqf1": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "19s576wcqf1-0.mp3",
      },
      {
        voice: "shimmer",
        file: "19s576wcqf1-1.mp3",
      },
      {
        voice: "alloy",
        file: "19s576wcqf1-2.mp3",
      },
      {
        voice: "shimmer",
        file: "19s576wcqf1-3.mp3",
      },
      {
        voice: "alloy",
        file: "19s576wcqf1-4.mp3",
      },
    ],
  },
  "1be96t9tkaf": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1be96t9tkaf-0.mp3",
      },
      {
        voice: "onyx",
        file: "1be96t9tkaf-1.mp3",
      },
      {
        voice: "nova",
        file: "1be96t9tkaf-2.mp3",
      },
      {
        voice: "onyx",
        file: "1be96t9tkaf-3.mp3",
      },
      {
        voice: "alloy",
        file: "1be96t9tkaf-4.mp3",
      },
    ],
  },
  "2avpqah5yva": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2avpqah5yva-0.mp3",
      },
      {
        voice: "shimmer",
        file: "2avpqah5yva-1.mp3",
      },
      {
        voice: "alloy",
        file: "2avpqah5yva-2.mp3",
      },
      {
        voice: "shimmer",
        file: "2avpqah5yva-3.mp3",
      },
      {
        voice: "alloy",
        file: "2avpqah5yva-4.mp3",
      },
    ],
  },
  "1natx47zyux": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1natx47zyux-0.mp3",
      },
      {
        voice: "onyx",
        file: "1natx47zyux-1.mp3",
      },
      {
        voice: "nova",
        file: "1natx47zyux-2.mp3",
      },
      {
        voice: "onyx",
        file: "1natx47zyux-3.mp3",
      },
      {
        voice: "alloy",
        file: "1natx47zyux-4.mp3",
      },
    ],
  },
  if6k48qlc7: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "if6k48qlc7-0.mp3",
      },
      {
        voice: "alloy",
        file: "if6k48qlc7-1.mp3",
      },
      {
        voice: "shimmer",
        file: "if6k48qlc7-2.mp3",
      },
      {
        voice: "alloy",
        file: "if6k48qlc7-3.mp3",
      },
      {
        voice: "alloy",
        file: "if6k48qlc7-4.mp3",
      },
    ],
  },
  "1kg9xd2c0r9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1kg9xd2c0r9-0.mp3",
      },
      {
        voice: "nova",
        file: "1kg9xd2c0r9-1.mp3",
      },
      {
        voice: "onyx",
        file: "1kg9xd2c0r9-2.mp3",
      },
      {
        voice: "nova",
        file: "1kg9xd2c0r9-3.mp3",
      },
      {
        voice: "alloy",
        file: "1kg9xd2c0r9-4.mp3",
      },
    ],
  },
  bn7kq94htz: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "bn7kq94htz-0.mp3",
      },
      {
        voice: "alloy",
        file: "bn7kq94htz-1.mp3",
      },
      {
        voice: "shimmer",
        file: "bn7kq94htz-2.mp3",
      },
      {
        voice: "alloy",
        file: "bn7kq94htz-3.mp3",
      },
      {
        voice: "alloy",
        file: "bn7kq94htz-4.mp3",
      },
    ],
  },
  "1d0jv38b1ls": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1d0jv38b1ls-0.mp3",
      },
      {
        voice: "onyx",
        file: "1d0jv38b1ls-1.mp3",
      },
      {
        voice: "nova",
        file: "1d0jv38b1ls-2.mp3",
      },
      {
        voice: "onyx",
        file: "1d0jv38b1ls-3.mp3",
      },
      {
        voice: "alloy",
        file: "1d0jv38b1ls-4.mp3",
      },
    ],
  },
  "1inwf1lihzu": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1inwf1lihzu-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1inwf1lihzu-1.mp3",
      },
      {
        voice: "alloy",
        file: "1inwf1lihzu-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1inwf1lihzu-3.mp3",
      },
      {
        voice: "alloy",
        file: "1inwf1lihzu-4.mp3",
      },
    ],
  },
  "27u164q4kls": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "27u164q4kls-0.mp3",
      },
      {
        voice: "onyx",
        file: "27u164q4kls-1.mp3",
      },
      {
        voice: "nova",
        file: "27u164q4kls-2.mp3",
      },
      {
        voice: "onyx",
        file: "27u164q4kls-3.mp3",
      },
      {
        voice: "alloy",
        file: "27u164q4kls-4.mp3",
      },
    ],
  },
  n08diinzkm: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "n08diinzkm-0.mp3",
      },
      {
        voice: "shimmer",
        file: "n08diinzkm-1.mp3",
      },
      {
        voice: "alloy",
        file: "n08diinzkm-2.mp3",
      },
      {
        voice: "shimmer",
        file: "n08diinzkm-3.mp3",
      },
      {
        voice: "alloy",
        file: "n08diinzkm-4.mp3",
      },
    ],
  },
  "2ew044pbsnq": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2ew044pbsnq-0.mp3",
      },
      {
        voice: "onyx",
        file: "2ew044pbsnq-1.mp3",
      },
      {
        voice: "nova",
        file: "2ew044pbsnq-2.mp3",
      },
      {
        voice: "onyx",
        file: "2ew044pbsnq-3.mp3",
      },
      {
        voice: "alloy",
        file: "2ew044pbsnq-4.mp3",
      },
    ],
  },
  "19xa13gkajb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "19xa13gkajb-0.mp3",
      },
      {
        voice: "shimmer",
        file: "19xa13gkajb-1.mp3",
      },
      {
        voice: "alloy",
        file: "19xa13gkajb-2.mp3",
      },
      {
        voice: "shimmer",
        file: "19xa13gkajb-3.mp3",
      },
      {
        voice: "alloy",
        file: "19xa13gkajb-4.mp3",
      },
    ],
  },
  "2g9cck57xew": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2g9cck57xew-0.mp3",
      },
      {
        voice: "onyx",
        file: "2g9cck57xew-1.mp3",
      },
      {
        voice: "nova",
        file: "2g9cck57xew-2.mp3",
      },
      {
        voice: "onyx",
        file: "2g9cck57xew-3.mp3",
      },
      {
        voice: "alloy",
        file: "2g9cck57xew-4.mp3",
      },
    ],
  },
  tulj6e08qe: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "tulj6e08qe-0.mp3",
      },
      {
        voice: "shimmer",
        file: "tulj6e08qe-1.mp3",
      },
      {
        voice: "alloy",
        file: "tulj6e08qe-2.mp3",
      },
      {
        voice: "shimmer",
        file: "tulj6e08qe-3.mp3",
      },
      {
        voice: "alloy",
        file: "tulj6e08qe-4.mp3",
      },
    ],
  },
  hzzn5xnkgw: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "hzzn5xnkgw-0.mp3",
      },
      {
        voice: "onyx",
        file: "hzzn5xnkgw-1.mp3",
      },
      {
        voice: "nova",
        file: "hzzn5xnkgw-2.mp3",
      },
      {
        voice: "onyx",
        file: "hzzn5xnkgw-3.mp3",
      },
      {
        voice: "alloy",
        file: "hzzn5xnkgw-4.mp3",
      },
    ],
  },
  aho3ebj1wr: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "aho3ebj1wr-0.mp3",
      },
      {
        voice: "shimmer",
        file: "aho3ebj1wr-1.mp3",
      },
      {
        voice: "alloy",
        file: "aho3ebj1wr-2.mp3",
      },
      {
        voice: "shimmer",
        file: "aho3ebj1wr-3.mp3",
      },
      {
        voice: "alloy",
        file: "aho3ebj1wr-4.mp3",
      },
    ],
  },
  "1n4j7v0jhcu": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1n4j7v0jhcu-0.mp3",
      },
      {
        voice: "onyx",
        file: "1n4j7v0jhcu-1.mp3",
      },
      {
        voice: "nova",
        file: "1n4j7v0jhcu-2.mp3",
      },
      {
        voice: "onyx",
        file: "1n4j7v0jhcu-3.mp3",
      },
      {
        voice: "alloy",
        file: "1n4j7v0jhcu-4.mp3",
      },
    ],
  },
  "1hpozmj3wxg": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1hpozmj3wxg-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1hpozmj3wxg-1.mp3",
      },
      {
        voice: "alloy",
        file: "1hpozmj3wxg-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1hpozmj3wxg-3.mp3",
      },
      {
        voice: "alloy",
        file: "1hpozmj3wxg-4.mp3",
      },
    ],
  },
  ub9ifmmxi0: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "ub9ifmmxi0-0.mp3",
      },
      {
        voice: "onyx",
        file: "ub9ifmmxi0-1.mp3",
      },
      {
        voice: "nova",
        file: "ub9ifmmxi0-2.mp3",
      },
      {
        voice: "onyx",
        file: "ub9ifmmxi0-3.mp3",
      },
      {
        voice: "alloy",
        file: "ub9ifmmxi0-4.mp3",
      },
    ],
  },
  oedoka39sr: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "oedoka39sr-0.mp3",
      },
      {
        voice: "shimmer",
        file: "oedoka39sr-1.mp3",
      },
      {
        voice: "alloy",
        file: "oedoka39sr-2.mp3",
      },
      {
        voice: "shimmer",
        file: "oedoka39sr-3.mp3",
      },
      {
        voice: "alloy",
        file: "oedoka39sr-4.mp3",
      },
    ],
  },
  x487ruyvfj: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "x487ruyvfj-0.mp3",
      },
      {
        voice: "onyx",
        file: "x487ruyvfj-1.mp3",
      },
      {
        voice: "nova",
        file: "x487ruyvfj-2.mp3",
      },
      {
        voice: "onyx",
        file: "x487ruyvfj-3.mp3",
      },
      {
        voice: "alloy",
        file: "x487ruyvfj-4.mp3",
      },
    ],
  },
  "1b6ar5uwr55": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1b6ar5uwr55-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1b6ar5uwr55-1.mp3",
      },
      {
        voice: "alloy",
        file: "1b6ar5uwr55-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1b6ar5uwr55-3.mp3",
      },
      {
        voice: "alloy",
        file: "1b6ar5uwr55-4.mp3",
      },
    ],
  },
  thtl7npf3r: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "thtl7npf3r-0.mp3",
      },
      {
        voice: "onyx",
        file: "thtl7npf3r-1.mp3",
      },
      {
        voice: "nova",
        file: "thtl7npf3r-2.mp3",
      },
      {
        voice: "onyx",
        file: "thtl7npf3r-3.mp3",
      },
      {
        voice: "alloy",
        file: "thtl7npf3r-4.mp3",
      },
    ],
  },
  "14xvsl1pdw6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "14xvsl1pdw6-0.mp3",
      },
      {
        voice: "shimmer",
        file: "14xvsl1pdw6-1.mp3",
      },
      {
        voice: "alloy",
        file: "14xvsl1pdw6-2.mp3",
      },
      {
        voice: "shimmer",
        file: "14xvsl1pdw6-3.mp3",
      },
      {
        voice: "alloy",
        file: "14xvsl1pdw6-4.mp3",
      },
    ],
  },
  "1z93us9rdsa": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1z93us9rdsa-0.mp3",
      },
      {
        voice: "onyx",
        file: "1z93us9rdsa-1.mp3",
      },
      {
        voice: "nova",
        file: "1z93us9rdsa-2.mp3",
      },
      {
        voice: "onyx",
        file: "1z93us9rdsa-3.mp3",
      },
      {
        voice: "alloy",
        file: "1z93us9rdsa-4.mp3",
      },
    ],
  },
  "4lyi17sshb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "4lyi17sshb-0.mp3",
      },
      {
        voice: "alloy",
        file: "4lyi17sshb-1.mp3",
      },
      {
        voice: "shimmer",
        file: "4lyi17sshb-2.mp3",
      },
      {
        voice: "alloy",
        file: "4lyi17sshb-3.mp3",
      },
      {
        voice: "alloy",
        file: "4lyi17sshb-4.mp3",
      },
    ],
  },
  kaiqytjz05: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "kaiqytjz05-0.mp3",
      },
      {
        voice: "nova",
        file: "kaiqytjz05-1.mp3",
      },
      {
        voice: "onyx",
        file: "kaiqytjz05-2.mp3",
      },
      {
        voice: "nova",
        file: "kaiqytjz05-3.mp3",
      },
      {
        voice: "alloy",
        file: "kaiqytjz05-4.mp3",
      },
    ],
  },
  "1m7cd7hff7y": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1m7cd7hff7y-0.mp3",
      },
      {
        voice: "alloy",
        file: "1m7cd7hff7y-1.mp3",
      },
      {
        voice: "shimmer",
        file: "1m7cd7hff7y-2.mp3",
      },
      {
        voice: "alloy",
        file: "1m7cd7hff7y-3.mp3",
      },
      {
        voice: "alloy",
        file: "1m7cd7hff7y-4.mp3",
      },
    ],
  },
  "1rm1m08gt8p": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1rm1m08gt8p-0.mp3",
      },
      {
        voice: "nova",
        file: "1rm1m08gt8p-1.mp3",
      },
      {
        voice: "onyx",
        file: "1rm1m08gt8p-2.mp3",
      },
      {
        voice: "nova",
        file: "1rm1m08gt8p-3.mp3",
      },
      {
        voice: "alloy",
        file: "1rm1m08gt8p-4.mp3",
      },
    ],
  },
  byv2xxjmgy: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "byv2xxjmgy-0.mp3",
      },
      {
        voice: "shimmer",
        file: "byv2xxjmgy-1.mp3",
      },
      {
        voice: "alloy",
        file: "byv2xxjmgy-2.mp3",
      },
      {
        voice: "shimmer",
        file: "byv2xxjmgy-3.mp3",
      },
      {
        voice: "alloy",
        file: "byv2xxjmgy-4.mp3",
      },
    ],
  },
  ag109h32mx: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "ag109h32mx-0.mp3",
      },
      {
        voice: "onyx",
        file: "ag109h32mx-1.mp3",
      },
      {
        voice: "nova",
        file: "ag109h32mx-2.mp3",
      },
      {
        voice: "onyx",
        file: "ag109h32mx-3.mp3",
      },
      {
        voice: "alloy",
        file: "ag109h32mx-4.mp3",
      },
    ],
  },
  "158ss3u9xwd": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "158ss3u9xwd-0.mp3",
      },
      {
        voice: "shimmer",
        file: "158ss3u9xwd-1.mp3",
      },
      {
        voice: "alloy",
        file: "158ss3u9xwd-2.mp3",
      },
      {
        voice: "shimmer",
        file: "158ss3u9xwd-3.mp3",
      },
      {
        voice: "alloy",
        file: "158ss3u9xwd-4.mp3",
      },
    ],
  },
  "19utbnw68vo": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "19utbnw68vo-0.mp3",
      },
      {
        voice: "onyx",
        file: "19utbnw68vo-1.mp3",
      },
      {
        voice: "nova",
        file: "19utbnw68vo-2.mp3",
      },
      {
        voice: "onyx",
        file: "19utbnw68vo-3.mp3",
      },
      {
        voice: "alloy",
        file: "19utbnw68vo-4.mp3",
      },
    ],
  },
  b7znzth6od: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "b7znzth6od-0.mp3",
      },
      {
        voice: "shimmer",
        file: "b7znzth6od-1.mp3",
      },
      {
        voice: "alloy",
        file: "b7znzth6od-2.mp3",
      },
      {
        voice: "shimmer",
        file: "b7znzth6od-3.mp3",
      },
      {
        voice: "alloy",
        file: "b7znzth6od-4.mp3",
      },
    ],
  },
  "1h19ibm1q63": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1h19ibm1q63-0.mp3",
      },
      {
        voice: "onyx",
        file: "1h19ibm1q63-1.mp3",
      },
      {
        voice: "nova",
        file: "1h19ibm1q63-2.mp3",
      },
      {
        voice: "onyx",
        file: "1h19ibm1q63-3.mp3",
      },
      {
        voice: "alloy",
        file: "1h19ibm1q63-4.mp3",
      },
    ],
  },
  "20z6ukvnjqo": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "20z6ukvnjqo-0.mp3",
      },
      {
        voice: "alloy",
        file: "20z6ukvnjqo-1.mp3",
      },
      {
        voice: "shimmer",
        file: "20z6ukvnjqo-2.mp3",
      },
      {
        voice: "alloy",
        file: "20z6ukvnjqo-3.mp3",
      },
      {
        voice: "alloy",
        file: "20z6ukvnjqo-4.mp3",
      },
    ],
  },
  "1ndmn42quur": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1ndmn42quur-0.mp3",
      },
      {
        voice: "nova",
        file: "1ndmn42quur-1.mp3",
      },
      {
        voice: "onyx",
        file: "1ndmn42quur-2.mp3",
      },
      {
        voice: "nova",
        file: "1ndmn42quur-3.mp3",
      },
      {
        voice: "alloy",
        file: "1ndmn42quur-4.mp3",
      },
    ],
  },
  "1e6k57bmqoe": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1e6k57bmqoe-0.mp3",
      },
      {
        voice: "shimmer",
        file: "1e6k57bmqoe-1.mp3",
      },
      {
        voice: "alloy",
        file: "1e6k57bmqoe-2.mp3",
      },
      {
        voice: "shimmer",
        file: "1e6k57bmqoe-3.mp3",
      },
      {
        voice: "alloy",
        file: "1e6k57bmqoe-4.mp3",
      },
    ],
  },
  u4u22diefw: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "u4u22diefw-0.mp3",
      },
      {
        voice: "onyx",
        file: "u4u22diefw-1.mp3",
      },
      {
        voice: "nova",
        file: "u4u22diefw-2.mp3",
      },
      {
        voice: "onyx",
        file: "u4u22diefw-3.mp3",
      },
      {
        voice: "alloy",
        file: "u4u22diefw-4.mp3",
      },
    ],
  },
  "14py4vshc48": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "14py4vshc48-0.mp3",
      },
      {
        voice: "shimmer",
        file: "14py4vshc48-1.mp3",
      },
      {
        voice: "alloy",
        file: "14py4vshc48-2.mp3",
      },
      {
        voice: "shimmer",
        file: "14py4vshc48-3.mp3",
      },
      {
        voice: "alloy",
        file: "14py4vshc48-4.mp3",
      },
    ],
  },
  g2q1pr0ni2: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "g2q1pr0ni2-0.mp3",
      },
      {
        voice: "onyx",
        file: "g2q1pr0ni2-1.mp3",
      },
      {
        voice: "nova",
        file: "g2q1pr0ni2-2.mp3",
      },
      {
        voice: "onyx",
        file: "g2q1pr0ni2-3.mp3",
      },
      {
        voice: "alloy",
        file: "g2q1pr0ni2-4.mp3",
      },
    ],
  },
  "21yh2im1qc0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "21yh2im1qc0-0.mp3",
      },
      {
        voice: "alloy",
        file: "21yh2im1qc0-1.mp3",
      },
      {
        voice: "shimmer",
        file: "21yh2im1qc0-2.mp3",
      },
      {
        voice: "alloy",
        file: "21yh2im1qc0-3.mp3",
      },
      {
        voice: "alloy",
        file: "21yh2im1qc0-4.mp3",
      },
    ],
  },
  iw7fxud8om: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "iw7fxud8om-0.mp3",
      },
      {
        voice: "nova",
        file: "iw7fxud8om-1.mp3",
      },
      {
        voice: "onyx",
        file: "iw7fxud8om-2.mp3",
      },
      {
        voice: "nova",
        file: "iw7fxud8om-3.mp3",
      },
      {
        voice: "alloy",
        file: "iw7fxud8om-4.mp3",
      },
    ],
  },
  "21c6wd3ib0z": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "21c6wd3ib0z-0.mp3",
      },
      {
        voice: "alloy",
        file: "21c6wd3ib0z-1.mp3",
      },
    ],
  },
  wdgh6l059q: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "wdgh6l059q-0.mp3",
      },
      {
        voice: "alloy",
        file: "wdgh6l059q-1.mp3",
      },
    ],
  },
  "3cb9hfhqct": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "3cb9hfhqct-0.mp3",
      },
      {
        voice: "alloy",
        file: "3cb9hfhqct-1.mp3",
      },
    ],
  },
  ozks29c4fg: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "ozks29c4fg-0.mp3",
      },
      {
        voice: "alloy",
        file: "ozks29c4fg-1.mp3",
      },
    ],
  },
  "22fop6ycatw": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "22fop6ycatw-0.mp3",
      },
      {
        voice: "alloy",
        file: "22fop6ycatw-1.mp3",
      },
    ],
  },
  "2anch8fknk4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2anch8fknk4-0.mp3",
      },
      {
        voice: "alloy",
        file: "2anch8fknk4-1.mp3",
      },
    ],
  },
  "1t2efo6prtl": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1t2efo6prtl-0.mp3",
      },
      {
        voice: "alloy",
        file: "1t2efo6prtl-1.mp3",
      },
    ],
  },
  pxjif3isy2: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "pxjif3isy2-0.mp3",
      },
      {
        voice: "alloy",
        file: "pxjif3isy2-1.mp3",
      },
    ],
  },
  rnrd4dmxas: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "rnrd4dmxas-0.mp3",
      },
      {
        voice: "alloy",
        file: "rnrd4dmxas-1.mp3",
      },
    ],
  },
  "3ruz9c41ct": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "3ruz9c41ct-0.mp3",
      },
      {
        voice: "alloy",
        file: "3ruz9c41ct-1.mp3",
      },
    ],
  },
  "11l3ptszo79": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "11l3ptszo79-0.mp3",
      },
      {
        voice: "alloy",
        file: "11l3ptszo79-1.mp3",
      },
    ],
  },
  r44tin4nkw: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "r44tin4nkw-0.mp3",
      },
      {
        voice: "alloy",
        file: "r44tin4nkw-1.mp3",
      },
    ],
  },
  hsztp9ie1r: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "hsztp9ie1r-0.mp3",
      },
      {
        voice: "alloy",
        file: "hsztp9ie1r-1.mp3",
      },
    ],
  },
  uk26um3gu4: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "uk26um3gu4-0.mp3",
      },
      {
        voice: "alloy",
        file: "uk26um3gu4-1.mp3",
      },
    ],
  },
  "2g0auv639yr": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2g0auv639yr-0.mp3",
      },
      {
        voice: "alloy",
        file: "2g0auv639yr-1.mp3",
      },
    ],
  },
  "24ocku2smyf": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "24ocku2smyf-0.mp3",
      },
      {
        voice: "alloy",
        file: "24ocku2smyf-1.mp3",
      },
    ],
  },
  u8i9nol4e5: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "u8i9nol4e5-0.mp3",
      },
      {
        voice: "alloy",
        file: "u8i9nol4e5-1.mp3",
      },
    ],
  },
  "1hu66h3mkb0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1hu66h3mkb0-0.mp3",
      },
      {
        voice: "alloy",
        file: "1hu66h3mkb0-1.mp3",
      },
    ],
  },
  "2e9yl9syc6c": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2e9yl9syc6c-0.mp3",
      },
      {
        voice: "alloy",
        file: "2e9yl9syc6c-1.mp3",
      },
    ],
  },
  "1tvuljvynqv": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1tvuljvynqv-0.mp3",
      },
      {
        voice: "alloy",
        file: "1tvuljvynqv-1.mp3",
      },
    ],
  },
  fv9e1hiik3: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "fv9e1hiik3-0.mp3",
      },
      {
        voice: "alloy",
        file: "fv9e1hiik3-1.mp3",
      },
    ],
  },
  "117cqav43ka": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "117cqav43ka-0.mp3",
      },
      {
        voice: "alloy",
        file: "117cqav43ka-1.mp3",
      },
    ],
  },
  "1xtlbjhm0nf": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1xtlbjhm0nf-0.mp3",
      },
      {
        voice: "alloy",
        file: "1xtlbjhm0nf-1.mp3",
      },
    ],
  },
  "1d3nhkc91t4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1d3nhkc91t4-0.mp3",
      },
      {
        voice: "alloy",
        file: "1d3nhkc91t4-1.mp3",
      },
    ],
  },
  "15ql26s6ssj": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "15ql26s6ssj-0.mp3",
      },
      {
        voice: "alloy",
        file: "15ql26s6ssj-1.mp3",
      },
    ],
  },
  "27kmge33uxl": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "27kmge33uxl-0.mp3",
      },
      {
        voice: "alloy",
        file: "27kmge33uxl-1.mp3",
      },
    ],
  },
  "24p7duu15ml": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "24p7duu15ml-0.mp3",
      },
      {
        voice: "alloy",
        file: "24p7duu15ml-1.mp3",
      },
    ],
  },
  "1jvw9ghromc": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1jvw9ghromc-0.mp3",
      },
      {
        voice: "alloy",
        file: "1jvw9ghromc-1.mp3",
      },
    ],
  },
  wh73dgg48j: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "wh73dgg48j-0.mp3",
      },
      {
        voice: "alloy",
        file: "wh73dgg48j-1.mp3",
      },
    ],
  },
  "13cw9aaxs0v": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "13cw9aaxs0v-0.mp3",
      },
      {
        voice: "alloy",
        file: "13cw9aaxs0v-1.mp3",
      },
    ],
  },
  "255wizvopb2": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "255wizvopb2-0.mp3",
      },
      {
        voice: "alloy",
        file: "255wizvopb2-1.mp3",
      },
    ],
  },
  "6zg1pyfyh0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "6zg1pyfyh0-0.mp3",
      },
      {
        voice: "alloy",
        file: "6zg1pyfyh0-1.mp3",
      },
    ],
  },
  sl86nvr5f9: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "sl86nvr5f9-0.mp3",
      },
      {
        voice: "alloy",
        file: "sl86nvr5f9-1.mp3",
      },
    ],
  },
  "12p7nuo4qat": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "12p7nuo4qat-0.mp3",
      },
      {
        voice: "alloy",
        file: "12p7nuo4qat-1.mp3",
      },
    ],
  },
  "15tyrkkva4u": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "15tyrkkva4u-0.mp3",
      },
      {
        voice: "alloy",
        file: "15tyrkkva4u-1.mp3",
      },
    ],
  },
  id293kz4we: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "id293kz4we-0.mp3",
      },
      {
        voice: "alloy",
        file: "id293kz4we-1.mp3",
      },
    ],
  },
  "1k3ojgynrn4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1k3ojgynrn4-0.mp3",
      },
      {
        voice: "alloy",
        file: "1k3ojgynrn4-1.mp3",
      },
    ],
  },
  "23jnjcyeq21": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "23jnjcyeq21-0.mp3",
      },
      {
        voice: "alloy",
        file: "23jnjcyeq21-1.mp3",
      },
    ],
  },
  "2bcg5o9aobs": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2bcg5o9aobs-0.mp3",
      },
      {
        voice: "alloy",
        file: "2bcg5o9aobs-1.mp3",
      },
    ],
  },
  "4p4leampe9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "4p4leampe9-0.mp3",
      },
      {
        voice: "alloy",
        file: "4p4leampe9-1.mp3",
      },
    ],
  },
  "1ieufpfosie": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1ieufpfosie-0.mp3",
      },
      {
        voice: "alloy",
        file: "1ieufpfosie-1.mp3",
      },
    ],
  },
  "1s60xctiih0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1s60xctiih0-0.mp3",
      },
      {
        voice: "alloy",
        file: "1s60xctiih0-1.mp3",
      },
    ],
  },
  "5x7nwj4ec1": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "5x7nwj4ec1-0.mp3",
      },
      {
        voice: "alloy",
        file: "5x7nwj4ec1-1.mp3",
      },
    ],
  },
  "9y106a3cub": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "9y106a3cub-0.mp3",
      },
      {
        voice: "alloy",
        file: "9y106a3cub-1.mp3",
      },
    ],
  },
  g1k6lvvixa: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "g1k6lvvixa-0.mp3",
      },
      {
        voice: "alloy",
        file: "g1k6lvvixa-1.mp3",
      },
    ],
  },
  "2afcbbpajhh": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2afcbbpajhh-0.mp3",
      },
      {
        voice: "alloy",
        file: "2afcbbpajhh-1.mp3",
      },
    ],
  },
  "15w8u847wmb": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "15w8u847wmb-0.mp3",
      },
      {
        voice: "alloy",
        file: "15w8u847wmb-1.mp3",
      },
    ],
  },
  "236do9x1kc4": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "236do9x1kc4-0.mp3",
      },
      {
        voice: "alloy",
        file: "236do9x1kc4-1.mp3",
      },
    ],
  },
  "18qn147xfvf": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "18qn147xfvf-0.mp3",
      },
      {
        voice: "alloy",
        file: "18qn147xfvf-1.mp3",
      },
    ],
  },
  oz144pt62m: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "oz144pt62m-0.mp3",
      },
      {
        voice: "alloy",
        file: "oz144pt62m-1.mp3",
      },
    ],
  },
  "1o9tye3nt11": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1o9tye3nt11-0.mp3",
      },
      {
        voice: "alloy",
        file: "1o9tye3nt11-1.mp3",
      },
    ],
  },
  z9lmno9dz1: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "z9lmno9dz1-0.mp3",
      },
      {
        voice: "alloy",
        file: "z9lmno9dz1-1.mp3",
      },
    ],
  },
  "28g3mly3wni": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "28g3mly3wni-0.mp3",
      },
      {
        voice: "alloy",
        file: "28g3mly3wni-1.mp3",
      },
    ],
  },
  "2aj8qt5zmmc": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2aj8qt5zmmc-0.mp3",
      },
      {
        voice: "alloy",
        file: "2aj8qt5zmmc-1.mp3",
      },
    ],
  },
  adxra71snm: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "adxra71snm-0.mp3",
      },
      {
        voice: "alloy",
        file: "adxra71snm-1.mp3",
      },
    ],
  },
  "113zt9hyw21": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "113zt9hyw21-0.mp3",
      },
      {
        voice: "alloy",
        file: "113zt9hyw21-1.mp3",
      },
    ],
  },
  itrt129zuv: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "itrt129zuv-0.mp3",
      },
      {
        voice: "alloy",
        file: "itrt129zuv-1.mp3",
      },
    ],
  },
  "1llrp23hr8z": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1llrp23hr8z-0.mp3",
      },
      {
        voice: "alloy",
        file: "1llrp23hr8z-1.mp3",
      },
    ],
  },
  "29q43ut79t5": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "29q43ut79t5-0.mp3",
      },
      {
        voice: "alloy",
        file: "29q43ut79t5-1.mp3",
      },
    ],
  },
  "17j0ga7jprx": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "17j0ga7jprx-0.mp3",
      },
      {
        voice: "alloy",
        file: "17j0ga7jprx-1.mp3",
      },
    ],
  },
  "1naeti8lg5m": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1naeti8lg5m-0.mp3",
      },
      {
        voice: "alloy",
        file: "1naeti8lg5m-1.mp3",
      },
    ],
  },
  "1s1k8f9p2w3": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "1s1k8f9p2w3-0.mp3",
      },
      {
        voice: "alloy",
        file: "1s1k8f9p2w3-1.mp3",
      },
    ],
  },
  "2aa5gyjgdbg": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "2aa5gyjgdbg-0.mp3",
      },
      {
        voice: "alloy",
        file: "2aa5gyjgdbg-1.mp3",
      },
    ],
  },
  "1071g2iiz7k": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1071g2iiz7k-0.mp3",
      },
      {
        voice: "alloy",
        file: "1071g2iiz7k-1.mp3",
      },
    ],
  },
  "13tqveu6b1w": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "13tqveu6b1w-0.mp3",
      },
      {
        voice: "alloy",
        file: "13tqveu6b1w-1.mp3",
      },
    ],
  },
  "17iudiaqyu7": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "17iudiaqyu7-0.mp3",
      },
      {
        voice: "alloy",
        file: "17iudiaqyu7-1.mp3",
      },
    ],
  },
  n4abyffzb1: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "n4abyffzb1-0.mp3",
      },
      {
        voice: "alloy",
        file: "n4abyffzb1-1.mp3",
      },
    ],
  },
  "1jkkwl18yg7": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1jkkwl18yg7-0.mp3",
      },
      {
        voice: "alloy",
        file: "1jkkwl18yg7-1.mp3",
      },
    ],
  },
  "155j1rf4cdn": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "155j1rf4cdn-0.mp3",
      },
      {
        voice: "alloy",
        file: "155j1rf4cdn-1.mp3",
      },
    ],
  },
  "28wshgmlh8i": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "28wshgmlh8i-0.mp3",
      },
      {
        voice: "alloy",
        file: "28wshgmlh8i-1.mp3",
      },
    ],
  },
  "250kz85b79c": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "250kz85b79c-0.mp3",
      },
      {
        voice: "alloy",
        file: "250kz85b79c-1.mp3",
      },
    ],
  },
  "1tihflc2kbx": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1tihflc2kbx-0.mp3",
      },
      {
        voice: "alloy",
        file: "1tihflc2kbx-1.mp3",
      },
    ],
  },
  "2gmb4xyuad9": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "2gmb4xyuad9-0.mp3",
      },
      {
        voice: "alloy",
        file: "2gmb4xyuad9-1.mp3",
      },
    ],
  },
  "2d3zeg1122d": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "2d3zeg1122d-0.mp3",
      },
      {
        voice: "alloy",
        file: "2d3zeg1122d-1.mp3",
      },
    ],
  },
  ti6wycb6v1: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "ti6wycb6v1-0.mp3",
      },
      {
        voice: "alloy",
        file: "ti6wycb6v1-1.mp3",
      },
    ],
  },
  "282ftywpp91": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "282ftywpp91-0.mp3",
      },
      {
        voice: "alloy",
        file: "282ftywpp91-1.mp3",
      },
    ],
  },
  "1gczstmvbyw": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1gczstmvbyw-0.mp3",
      },
      {
        voice: "alloy",
        file: "1gczstmvbyw-1.mp3",
      },
    ],
  },
  t97webc4rm: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "t97webc4rm-0.mp3",
      },
      {
        voice: "alloy",
        file: "t97webc4rm-1.mp3",
      },
    ],
  },
  "1tubk8n5nbp": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "1tubk8n5nbp-0.mp3",
      },
      {
        voice: "alloy",
        file: "1tubk8n5nbp-1.mp3",
      },
    ],
  },
  yd0jiponu0: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "yd0jiponu0-0.mp3",
      },
      {
        voice: "alloy",
        file: "yd0jiponu0-1.mp3",
      },
    ],
  },
  z9intbz56a: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "z9intbz56a-0.mp3",
      },
      {
        voice: "alloy",
        file: "z9intbz56a-1.mp3",
      },
    ],
  },
  "11rdr0az8mt": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "alloy",
        file: "11rdr0az8mt-0.mp3",
      },
      {
        voice: "alloy",
        file: "11rdr0az8mt-1.mp3",
      },
    ],
  },
  se0ef8sj5h: {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "nova",
        file: "se0ef8sj5h-0.mp3",
      },
      {
        voice: "alloy",
        file: "se0ef8sj5h-1.mp3",
      },
    ],
  },
  "1n67sq01yg6": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "onyx",
        file: "1n67sq01yg6-0.mp3",
      },
      {
        voice: "alloy",
        file: "1n67sq01yg6-1.mp3",
      },
    ],
  },
  "1fnmd9a0zl0": {
    model: "gpt-4o-mini-tts",
    segments: [
      {
        voice: "shimmer",
        file: "1fnmd9a0zl0-0.mp3",
      },
      {
        voice: "alloy",
        file: "1fnmd9a0zl0-1.mp3",
      },
    ],
  },
};
