// Generated by scripts/generate-audio.ts — do not edit by hand.
// Run `bun run generate:audio` (with OPENAI_API_KEY set) to populate this file.

export interface AudioManifestSegment {
  voice: string;
  file: string;
}

export interface AudioManifestEntry {
  model: string;
  segments: AudioManifestSegment[];
}

export const audioManifest: Record<string, AudioManifestEntry> = {};
